### ISSUE TITLE
Thaumcraft Wands

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#491] opened 2016-02-26 09:18 UTC
- Gold Banded Great wood Wand ( All Wands)
  +Recipe in Nei Shows Thaumcraft Gold caps.
     +Without looking thoroughly through Nei one wouln't notice that it takes Gold Wand Caps from GT: NewHorizons 

Please disable incorrect recipes or change them to be correct to deter further confusion.

**Comment by Dream-Master** [comment] 2016-02-26 11:43
The recipes are redone all ready and available on Github already. Try the recipe already and if this happens again please post some screenshots i will looking into it.

**Comment by Teteros** [comment] 2016-02-26 11:44
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Thaumaturgy-1.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Thaumaturgy-2.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Thaumaturgy-3.zs
Related https://github.com/GTNewHorizons/NewHorizons/issues/485

**Comment by Dream-Master** [comment] 2016-02-26 11:48
@Teteros Thanks.

To add all scripts from Thaumcraft need this scripts too.

https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Golemancy.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Eldritch.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Basic.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Artifice.zs
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Alchemy.zs

**Comment by Dream-Master** [comment] 2016-02-26 17:57
@Goofyschooler 
I understand now what you mean. The problem is i can't hide the original Thaumcraft recipe with Modtweaker because Azanor the Mod Author add some code in his that some recipe a cant be remove. Thats why i add new Wand caps and make the Thaumcraft ones uncraftable. Not sure what we can do here more.

**Comment by Goofyschooler** [comment] 2016-02-27 15:38
@Dream-Master I guess one thing left is to ask azanor personally about how to disable his recipes that are conflicting with the new ones? My best guess though.

**Comment by Dream-Master** [comment] 2016-02-27 16:52
He dont want to change it.

https://github.com/jaredlll08/ModTweaker2/issues/210
https://github.com/jaredlll08/ModTweaker2/issues/16

This issue Azanor delete
https://github.com/Azanor/thaumcraft/issues/1532

**Comment by Goofyschooler** [comment] 2016-02-27 16:57
Because the mod isn't open source we can't change it... alright I guess he won this one then. Can you change the recipes in the nomicon for them? Maybe not hide the recipes in nei but change the ones in the nomicon. Because that's where you have togo anyways to research it.

**Comment by Dream-Master** [comment] 2016-02-27 17:05
I did ad it to the Book allready. Only my caps using the same texture then thaumcraft ones.

**Comment by Goofyschooler** [comment] 2016-02-27 17:11
Ohokay must not be in the update we are using then. Because it shows the wrong recipe. Not 100% sure on that will have to check it later

**Comment by Dream-Master** [comment] 2016-03-04 19:41
not sure what i can do here. I close it and if someone have a solution i will open it again.

**Closed by Dream-Master** 2016-03-04 19:41 UTC
Labels: question
