### ISSUE TITLE
Stemcells chickens can't be created

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4894] opened 2019-07-31 17:23 UTC
#### Which modpack version are you using?
Eta-live
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I'm trying to make this big red chickens which creates genetically modified eggs for stemcells.
#
#### What happened instead? (Attach screenshots if needed)
Brewery can accept 750l of liquid only, and recipe need 1332
#
#### What do you suggest instead/what changes do you propose?
Change the values to 750 liquid xp => 56 mobessence from 1332 liquid xp => 100 mobessence

![2019-07-31_20 19 03](https://user-images.githubusercontent.com/25028786/62233320-08483f00-b3d1-11e9-9d6a-f177304832f9.png)
![2019-07-31_20 19 13](https://user-images.githubusercontent.com/25028786/62233321-08e0d580-b3d1-11e9-9c25-ceeba290a482.png)

**Comment by boubou19** [comment] 2019-07-31 17:31
duplicate of #4867 
Use a processing array ;)

**Closed** 2019-07-31 17:35 UTC
