### ISSUE TITLE
GenDustry Combs Have No OreDirectory Name

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3498] opened 2018-08-24 05:57 UTC
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
*Add beeComb to an ME Ore Directory Export Bus
*All combs to be exported from ME.
#
#### What happend instead? (Attach screenshots if needed)
All combs except for GenDustry combs exported.
#
#### What do you suggest instead/what changes do you propose?
Add the beeComb ore directory name to GenDustry combs if possible.

**Comment by draknyte1** [comment] 2018-08-24 06:09
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/3358, fixed next release.

**Closed** 2018-08-24 06:27 UTC
Labels: FixedInDev, duplicate
