### ISSUE TITLE
Galacticraft frequency module cannot be autocrafted

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2195] opened 2017-11-14 13:25 UTC
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft "Frequency Module" in AE
#
#### What happend instead? (Attach screenshots if needed)
it cannot be crafted unless GC battery is taken from AE and put back
#
#### What do you suggest instead/what changes do you propose?
Battery recipe looks like this:
recipes.addShapeless(<GalacticraftCore:item.battery:*>, [<gregtech:gt.metaitem.01:32500>]);
I suggest to change it to 
recipes.addShapeless(<GalacticraftCore:item.battery:1>, [<gregtech:gt.metaitem.01:32500>]);

**Comment by ko5h** [comment] 2017-11-16 04:07
Duplicate of #2067

**Comment by repo-alt** [comment] 2017-11-16 09:59
Well, yes, this is indeed a duplicate, but a suggestion in the previous issue is strange, clearly this is a recipe error

**Closed** 2017-12-14 11:44 UTC
Labels: duplicate, FixedInDev
