### ISSUE TITLE
Dark Steel dust in EBF requires 4500K+ coils

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/NewHorizons#5672] opened 2020-03-02 03:06 UTC
#### Which modpack version are you using?
2.0.8.4
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Went took make dark steel from dark steel dust, coil requirements in the EBF seem way to high, or the quest in the MV tab is way off.
#
#### What happened instead? (Attach screenshots if needed)
https://i.imgur.com/008SQ0A.jpg

#
#### What do you suggest instead/what changes do you propose?
Change quest if Dark Steel really requires that high tier of an EBF coil, or lower heat requirements

**Comment by chochem** [comment] 2020-03-02 03:16
Duplicate of #5605

**Comment by Prometheus0000** [comment] 2020-03-02 03:52
I'm using 2.0.8.5dev, and it still says 4500K, was the fix included properly? End steel says 1800K which should have been changed in the same commit.

**Closed** 2020-03-10 11:10 UTC
Labels: FixedInDev, duplicate
