### ISSUE TITLE
Ore generator problem

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1909] opened 2017-09-01 12:33 UTC
I try to understand why i find so much ore centers without ore. I create flat world with 249 layers of stone and then teleported to 0, 0 coordinates and remove all stone, greg stone, rock hives and aura nodes. Then mark ore centers and get this image:
![GTNH](http://i.imgur.com/qz9dSpi.png) 
Why we get totally empty chunks? I can understand if we have empty ore mixes in modpack for some reason, but we shoul get small ores in every chunks, but we haven't it too. 

For comparsion i create almost same flatworld for last vanilla gregtech-5.09.31pre3:
Without ore center markes and with small ores:
![GT](http://i.imgur.com/ML84rgF.png)
Without small ores and with ore center markers:
![GT2](http://i.imgur.com/Z5YKeMv.png)
In vanilla gregtech we have ore mixes on every center if we have enough height, and in GTNH we have empty spaces even with 250 height.

**Comment by Dream-Master** [comment] 2017-09-01 12:56
@Technus, @JohannesGaessler did we have a different Oregen then GT main repo (exept the galacticraft compatibility we add with a own mod)?

**Comment by Dream-Master** [comment] 2017-09-01 12:58
@Usernm0 We using own ore mixes and i shift some gt ore mixes and take them to another dim like TF. Not fulle understand what is wrong and if i see gt ore world it is full with ore no empty space.

**Comment by DeForce** [comment] 2017-09-01 13:23
What is wrong - there are empty spaces.
You can see that in pure gregtech there is no clear/empty ore spawns, but on GTNH we see that there are gaps in ore generation.

**Comment by Dream-Master** [comment] 2017-09-01 13:37
@Usernm0 GTNH is a hard modpack so the ore mixes are very close together. And small ores are spawning too. I added oremixes in the overworld that are available up to y 250.

**Comment by DeForce** [comment] 2017-09-01 13:45
@Dream-Master 
> In vanilla gregtech we have ore mixes on every center if we have enough height, and in GTNH we have empty spaces even with 250 height.

**Comment by Dream-Master** [comment] 2017-09-01 13:51
Well maybe the oremixes not working like they should?

**Comment by Technus** [comment] 2017-09-01 13:53
Tin spawns above 100 (or 120) and has really high weight chance.

**Comment by Dream-Master** [comment] 2017-09-01 14:00
I mean 120 up to 250.

**Comment by Dream-Master** [comment] 2017-09-01 14:01
@Technus maybe some code are moved or wrong here thats why i ask.(compared to the GT origin repo)

**Comment by Dream-Master** [comment] 2017-09-01 14:09
![image](https://user-images.githubusercontent.com/2970688/29973473-f66951b0-8f2f-11e7-8b5a-2d37dda07529.png)
small coal ore 197y

**Comment by Dream-Master** [comment] 2017-09-01 14:10
Magnetite mix 145 y
![image](https://user-images.githubusercontent.com/2970688/29973510-13ba9c7e-8f30-11e7-92a9-3ae7016c96ef.png)

**Comment by Technus** [comment] 2017-09-01 14:12
Might be all that custom worldgens from other mods cascade generating map, would recommend check with only GTNH GT5u and its dependencies (coremod, yamcore)

**Comment by OneEyeMaker** [comment] 2017-09-01 16:00
@Dream-Master @Technus 
Also notice: ore vein centers shifted in negative X and Y.
In positive X and Y centers of ore veins located at 24 + 48n (n = 0, 1, 2...)
But in negative X and Y ore centers located at -8 - 48n (n = 0, 1, 2...)
So, ore veins near world center (0, 0) are located too close (2 chunks between ore veins instead of 3).

**Comment by Methes** [comment] 2017-09-01 16:23
OneEyeMaker that is normal and present in regular GT too.

**Comment by OneEyeMaker** [comment] 2017-09-01 16:39
@Methes 
Yes, but it's issue too. Both these issues can be fixed there and fix for cener shift can be sent to original repo.

**Comment by Ugachaga** [comment] 2017-09-01 17:04
@Methes 
https://github.com/Blood-Asp/GT5-Unofficial/commit/b9d4d15a0c2a49baeea34e1f17c336f404fb14f9
Doesn't this fix negative-coordinate vein generation?

**Comment by OneEyeMaker** [comment] 2017-09-02 04:12
Either this commit doesn't fix it or this commit doesn't exist in GTNH/GT5u repo (no one added/cherry-picked it).
See on screenshots of author of issue - in GTNH version vein centers located at -8, -56, -104.... (instead of -24, -72, -120,...)

**Comment by OneEyeMaker** [comment] 2017-09-02 04:20
Yes, this commit doesn't exist here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Worldgenerator.java#L95

**Comment by Technus** [comment] 2017-09-02 08:46
Yes i left it out due to old worldgen compat

**Comment by richardhendricks** [comment] 2017-09-07 19:51
Based on me just counting empty spaces, looks like ~33% of chunk centers are empty even with 256 height/

**Comment by bigbass1997** [comment] 2017-09-07 19:56
This page may answer many questions about the ore generation system. https://gtnh.miraheze.org/wiki/Ore_Generation

@richardhendricks It is possible for a vein to not be generated at all, regardless of how much terrain is available.

**Comment by richardhendricks** [comment] 2017-09-07 20:30
Given 1 chance at oregen, the odds of no ore on a fully-stone overworld is ~83% based on weights -most weights are in deepdark, so expected with 1 chance.  However, each additional chance multiples the odds of zero ore.  So 4 chances = .83*.83*.83*.83 = .83^4 = 47.5%.  After 256 chances, the odds of getting zero ore is so close to zero it's basically zero. Something else is possibly either not loading worldgen for that chunk, or causing it to drop out early.

**Comment by richardhendricks** [comment] 2017-09-07 21:58
Can you try enabling Gregtech Debug output?
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GregTech/GregTech.cfg
Set first Debug to true, line 21, in a backup of your modpack, and generate a new world.
This should cause Gregtech to output a line when it completes placing an ore:
        if (GT_Values.D1) {
            System.out.println("Generated Orevein: " + this.mWorldGenName);
        }
It might give us enough info to debug where the ores are disappearing from.

**Comment by richardhendricks** [comment] 2017-09-08 01:17
OK, so I enabled debug and ran worldgen with seed -1.  This text file is the debug output from gregtech, listing the locations of placed ore veins.  If an ore vein was attempted at too high a location, it will still get printed here.

[oregen_seed-1.txt](https://github.com/GTNewHorizons/NewHorizons/files/1286469/oregen_seed-1.txt)

mcedit is a little PITA so I am having troubles checking ore veins.  I did find a location -160, -400 that had no ore, including small ores, and no vein was attempted there.

**Comment by richardhendricks** [comment] 2017-09-08 01:35
-208.-352 is another orevein center with no orevein attempted, and no small ores at all.
-160.-400 is another orevein center with no orevein attempted, and no small ores at all.

-160, -352 has no orevein, attempted magnetite, small ores are present.  Surface level  55, magnetite 60-180, so no orevein is legit.

-208, -304 has no orevein, attempted chalcopyrite, small ores are present. Surface level 67, chalcopyrite probably from Copper and Tin, 180-250, so no orevein is legit.

1.5.1.1 btw.

**Comment by bigbass1997** [comment] 2017-09-08 01:39
This no small ores thing is quite strange, as whenever I have explored ore gen in the past, I always found small ores even in sections where no veins generated. This image is what I had posted on the (now outdated) mining guide and you can see that small ores did indeed generate http://i.imgur.com/DvDwkTe.png

**Comment by richardhendricks** [comment] 2017-09-08 01:51
No actually, I think they didn't.  Look at how some areas have very few small ores and some have higher density?  I think those small density areas are actually only ExtraBees hives.  At least that's what I see.  Can you recheck?

Also, how do you get that view?  Is that using mcedit?

**Comment by bigbass1997** [comment] 2017-09-08 02:04
That many bee hives? could be, but there are sections of higher density without veins. No clue where the world file is, if I ever have it still, was made a while back.

I used /cofh commands to remove all stone/granite/dirt/etc., then just opened JourneyMap, and took a screenshot of it.

**Comment by mitchej123** [comment] 2017-09-08 05:51
@richardhendricks clued me in on this, wanted to test it.

Machine was pretty overloaded when running this (3x MC instances, 1 server, 2 clients (1 MP, 1 SP to test) + various other things.

```
    public void generate(Random aRandom, int aX, int aZ, World aWorld, IChunkProvider aChunkGenerator, IChunkProvider aChunkProvider) {
        this.mList.add(new WorldGenContainer(new XSTR(aRandom.nextInt()), aX * 16, aZ * 16, ((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0, aWorld, aChunkGenerator, aChunkProvider, aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8).biomeName));
        GT_Log.out.println("ADD WorldGen - x:" + aX + " z:" + aZ + " SIZE: " + this.mList.size());
        if (!this.mIsGenerating) {
            this.mIsGenerating = true;
            int mList_sS=this.mList.size();
            for (int i = 0; i < mList_sS; i++) {
                WorldGenContainer toRun = (WorldGenContainer) this.mList.get(i);
                GT_Log.out.println("RUN WorldGen - x:" + toRun.mX + " z:" + aZ + "INDEX: " + i);
                toRun.run();
            }
            GT_Log.out.println("CLEAR WorldGen - x:" + aX + " z:" + aZ + " SIZE: " + this.mList.size());
            this.mList.clear();
            this.mIsGenerating = false;
        }
    }
```
```
grep ADD GregTech.log  | wc -l
804
grep RUN GregTech.log  | wc -l
374
grep CLEAR GregTech.log  | wc -l
374
```

**Comment by mitchej123** [comment] 2017-09-08 07:07
Pretty sure @richardhendricks is going to post a PR, but some further experimenting with him on discord, added synchronized access to the list, and always pop from the front.

The processing can still leave some on the queue when it finishes; but they'll get picked up the next time a new chunk is added -- would need to update the count and amount already processed in the loop to fix that.


```java
private final Object listLock = new Object();
    public void generate(Random aRandom, int aX, int aZ, World aWorld, IChunkProvider aChunkGenerator, IChunkProvider aChunkProvider) {
        synchronized (listLock)
        {
            this.mList.add(new WorldGenContainer(new XSTR(aRandom.nextInt()), aX * 16, aZ * 16, ((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0, aWorld, aChunkGenerator, aChunkProvider, aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8).biomeName));
            GT_Log.out.println("ADD WorldGen - x:" + aX + " z:" + aZ + " SIZE: " + this.mList.size());
        }
        if (!this.mIsGenerating) {
            this.mIsGenerating = true;
            int mList_sS=this.mList.size();
            for (int i = 0; i < mList_sS; i++) {
                WorldGenContainer toRun = (WorldGenContainer) this.mList.get(0);
                GT_Log.out.println("RUN WorldGen - x:" + toRun.mX/16 + " z:" + toRun.mZ/16 + " SIZE: " + this.mList.size());
                synchronized (listLock)
                {
                    this.mList.remove(0);
                }
                toRun.run();

            }
            this.mIsGenerating = false;
        }
    }
```

**Comment by bigbass1997** [comment] 2017-09-08 07:13
Ok so, just to explain what is going on, and why a PR is likely going to be created by @richardhendricks is: upon close inspection of the code, outside of the ore generation process, it seems there was a mistake when trying to make the GT_Worldgenerator class work faster whenever new chunks were created in a world.

It appears that https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Worldgenerator.java#L59 line 59 in this class is the cause for the 3x3 chunk sections that contain absolutely no veins or small ores.

This function is called by the Minecraft world generator whenever a new chunk is created, which appears to possibly run on a separate thread than the GT Worldgenerator object.

Whenever the function is called, simply put, a new "chunk" is added to an ArrayList. This list is periodically looped through using a standard for loop (no iterators). When the generation process starts inside the if statement, a variable is assigned as the size of the list at that moment. The loop then starts at 0 and runs until it has looped the number of times equal to the size of the list when it first started.

Inside the loop, the "chunk" is run so to attempt to generate ores in that chunk. This part is fine.

However, when the loop finishes, the list is cleared, instead of removing only the chunks that the loop just went through. The problem here is that while the loop was running, other chunks were being added to the list. The loop was designed to only run through the chunks that existed in the list when the loop started.

So the fix is to safely remove the processed chunks from the list, but still allow the generator to add new chunks to the list.

No iterators are being used here, so I figured that simply changing the function to this would work fine:
```Java
    public void generate(Random aRandom, int aX, int aZ, World aWorld, IChunkProvider aChunkGenerator, IChunkProvider aChunkProvider) {
        this.mList.add(new WorldGenContainer(new XSTR(aRandom.nextInt()), aX * 16, aZ * 16, ((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0, aWorld, aChunkGenerator, aChunkProvider, aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8).biomeName));
        if (!this.mIsGenerating) {
            this.mIsGenerating = true;
            int mList_sS=this.mList.size();
            for (int i = 0; i < mList_sS; i++) {
                ((Runnable) this.mList.get(0)).run();
                this.mList.remove(0);
            }
            this.mIsGenerating = false;
        }
    }
```

However, somehow this _might_ not be threadsafe, so using a synchronized approach might be a better solution.

**Comment by richardhendricks** [comment] 2017-09-08 07:25
Mitch and I collaborated and came up with some modifications to mostly fix the threadsafe issues.  There is still a potential for oregen to not happen if there are pending chunks and the server/SP is shut down, However in normal use the expectation is that chunk generation demand won't be that high so chunks get serviced pretty quickly.  Otherwise pending chunks will eventually get ore when another new chunk is requested.

Attached is a debug log with messages showing the chunks being added to the queue, being taken off the queue, and oregen results. For oreveins the first number is how many attempted blocks were placed, the second is how many actually were placed.  If a vein is in the air, the second number for all ores will be zero.

I'll send in a PR once I get it figured out, but here is the gist of the fix
```
//Add listLock object for synchronization purposes
	public static final Object listLock = new Object();
    //private static boolean gcAsteroids = true;

...

    public void generate(Random aRandom, int aX, int aZ, World aWorld, IChunkProvider aChunkGenerator, IChunkProvider aChunkProvider) {
        synchronized (listLock)
		{
			this.mList.add(new WorldGenContainer(new XSTR(aRandom.nextInt()), aX * 16, aZ * 16, ((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0, aWorld, aChunkGenerator, aChunkProvider, aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8).biomeName));
			if (D1) {GT_Log.out.println("ADD WorldGen chunk x:" + aX + " z:" + aZ + " SIZE: " + this.mList.size());}
        }
        if (!this.mIsGenerating) {
            this.mIsGenerating = true;
            int mList_sS=this.mList.size();
            for (int i = 0; i < mList_sS; i++) {
                WorldGenContainer toRun = (WorldGenContainer) this.mList.get(0);
                if (D1) {GT_Log.out.println("RUN WorldGen chunk x:" + toRun.mX/16 + " z:" + toRun.mZ/16 + " SIZE: " + this.mList.size());}
                synchronized (listLock)
                {
                    this.mList.remove(0);
                }
                toRun.run();
            }
            this.mIsGenerating = false;
        }
    }

```

**Comment by richardhendricks** [comment] 2017-09-08 07:47
PR issued

https://github.com/GTNewHorizons/GT5-Unofficial/pull/32

**Comment by richardhendricks** [comment] 2017-09-08 07:51
[gregtech-5.09.32.00.zip](https://github.com/GTNewHorizons/NewHorizons/files/1287119/gregtech-5.09.32.00.zip)

Compiled version of gregtech mod provided for testing. Remove gregtech from mods directory and replace with this file. 

For testing purposes only, use at own risk.

**Comment by Dream-Master** [comment] 2017-09-08 07:53
Say me if it work and what it change.

**Comment by Dream-Master** [comment] 2017-09-08 07:54
Make ore please not more dense as they now. Gtnh is a hard pack @richardhendricks

**Comment by Dream-Master** [comment] 2017-09-08 07:54
@Technus can you please review code thanks

**Comment by DeForce** [comment] 2017-09-08 07:57
This doesn't change any density, only the issue when ores are NOT generated at all.

**Comment by richardhendricks** [comment] 2017-09-08 08:01
This is a *bugfix*.  Without this fix, two machines running the same seed will not generate identical maps.  A heavily loaded server will NOT oregen new chunks. Someone running a potato is going to have *vastly* less ore than someone using a Ferrari. Is that behaviour we want? I doubt it.  

Look at the first post - those empty areas aren't because oregen decided NOT to put ore there, those empty areas are caused by the thread failing to keep up.  Someone with a faster/less loaded computer would get more ores than someone with a slow/busy computer.

This also would cause ores near a portal or worldspawn to be much rarer than further away, since at those times many chunks are being generated and likely losing ore.

If you feel that ores are too generous after this, adjust their heights or percentages.  You can still get empty zones - look at the log I provided and search for ,0 to find oreveins that tried to place but only found air. There are still plenty.

**Comment by Dream-Master** [comment] 2017-09-08 08:48
Ok understood how you fix work

**Comment by Dream-Master** [comment] 2017-09-28 10:43
@richardhendricks 
any news here. Is this fixed or is code added?

**Comment by richardhendricks** [comment] 2017-09-28 14:42
This issue is fixed and the pull request has been approved already.  1934 is still open.

**Comment by Dream-Master** [comment] 2017-09-28 17:03
@richardhendricks Can you push it to my gt branch too? Much easier to add then thanks

**Comment by richardhendricks** [comment] 2017-09-28 17:07
OK, I am confused. A pull request for this bug was issued and already accepted by you:
https://github.com/GTNewHorizons/GT5-Unofficial/pull/32

Do you want a PR for 1934?

**Comment by Dream-Master** [comment] 2017-09-28 17:09
Ah ok thanks. Yes send me one for the other. @richardhendricks

**Comment by richardhendricks** [comment] 2017-11-03 02:13
Re-introducing the chunk queuing fix for lost chunks.
Based on the tip of experimental as of 2017-11-02.

Usual disclaimers apply

No deposit, no return, no warranty, express or implied, may cause anal leakage, do not expose to small children, may cause severe liver damage, etc etc.

[gregtech-5.09.32.09.zip](https://github.com/GTNewHorizons/NewHorizons/files/1439907/gregtech-5.09.32.09.zip)

**Comment by richardhendricks** [comment] 2017-11-03 07:04
This version should have minor speed improvements. Most of the time wasted is in  the Minecraft related function calls, so to really improve speed would require reducing the number of ores per vein or making the MC calls faster.

Changes are: Remove constant values from inside for loops. Adjust if/elseif tree so MC common stones are done first vs after weird stones.


[gregtech-5.09.32.09 (2).zip](https://github.com/GTNewHorizons/NewHorizons/files/1440267/gregtech-5.09.32.09.2.zip)

**Comment by Dream-Master** [comment] 2017-11-03 08:49
@richardhendricks did you make pull requests to us gt fork?

**Comment by richardhendricks** [comment] 2017-11-03 15:12
No, not yet.  The performance difference I measured with my test program was very tiny. Next I want to test out filling the orevein in a different direction, in case we are hammering the caches. 

I dunno though, it seems like it may be more complex than that

https://minecraft.gamepedia.com/Chunk_format

Since GT is turning the block into a tile entity, the search within the chunk might be the major time sink.  Still we should attempt to optimize for cache lines by doing it the correct way.

The problem is that it is super difficult to determine performance differences in the live game since so much else is running, and there are so many variables.

**Comment by richardhendricks** [comment] 2018-01-21 19:12
New oregen has been merged with repo.

**Closed by richardhendricks** 2018-01-21 19:12 UTC
Labels: work in progress
