### ISSUE TITLE
Suggested default lepidopterology.cfg   - to decrease the butterfly spam/lag  We just killed off 2500 butterflies on our server.

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#2791] opened 2018-04-06 02:31 UTC
[lepidopterology.zip](https://github.com/GTNewHorizons/NewHorizons/files/1882502/lepidopterology.zip)

> # Configuration file

~CONFIG_VERSION: 1.0.0

butterfly {

    entities {
        # New butterflies will stay in item form and will not take flight once this limit is reached. [range: 0 ~ 5000, default: 1000]
        I:maximum=4

        # Allow butterflies to pollinate leaves. [default: true]
        B:pollination=true

        # Butterflies will stop natural spawning once this limit is reached. [range: 0 ~ 500, default: 100]
        I:spawn.limit=1
    }

}

**Comment by bartimaeusnek** [comment] 2018-04-06 06:29
On which version are you? We just debuffed the butterfly spawnammount with 2.0.3.0. If you host a dedicated server, feel free to change these valures yourself or test 2.0.3.1 once its out, its the Bugfix for 2.0.3.0 (will approx. be aviable in ~4Weeks)

**Comment by Dream-Master** [comment] 2018-04-07 10:07
reducing a bit to 50.

**Comment by noobyaran9** [comment] 2018-04-07 10:12
The issue is that the butterflies always flies north and when they reaches an unloaded chunk, they are not counted towards the limit which causes new ones to spawn. Changing the config by reducing the amount will only slow down the spawn rate but it won't fix the issue ultimately. 
And I don't think there is anyone out there is actually playing with butterflies, why not we just disable the whole butterfly thing and solve the issue once in for all.

# Butterflies. Shiny.
    B:lepidopterology=true ==> false

**Comment by Dream-Master** [comment] 2018-04-07 10:50
no i dont want to disable it.

**Closed** 2018-05-12 12:00 UTC
Labels: FixedInDev, need to be tested
