### ISSUE TITLE
Crash when clearing EnderIO fluid tank

### ISSUE THREAD

**Issue by Rokkitz** [GTNewHorizons/NewHorizons#5379] opened 2020-01-18 14:56 UTC
#### Which modpack version are you using?
GTNH 2083
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
When i try to clear an EnderIo fluid tank from water in my characters own crafting area (2x2)
#
#### What happened instead? (Attach screenshots if needed)
instant crash to menu.
#

**Comment by bartimaeusnek** [comment] 2020-01-18 14:57
read the discord accouncement please.

**Comment by draknyte1** [comment] 2020-01-18 14:57
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/5377#issuecomment-575903587

**Closed** 2020-01-18 14:57 UTC
