### ISSUE TITLE
[2.0] NEI gives wrong result for smelting ground basaltic mineral sand

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#1965] opened 2017-09-14 13:02 UTC
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
I smelted ground basaltic mineral sand, NEI says 1 ingot.
#
#### What happend instead? (Attach screenshots if needed)
I got 6 nuggets.  When forge hammered it says it gives an ingot, which still gives 6 nuggets.
#
#### What do you suggest instead/what changes do you propose?
Fix the readout on NEI or fix the output for the recipe.

**Comment by Methes** [comment] 2017-09-14 13:42
Duplicate of #1948.
Can be closed.

**Comment by Dream-Master** [comment] 2017-09-14 18:51
will check

**Closed** 2017-10-08 11:13 UTC
Labels: FixedInDev
