### ISSUE TITLE
GT++ centrifuge and electrolizer non responsive

### ISSUE THREAD

**Issue by whalas** [GTNewHorizons/NewHorizons#3295] opened 2018-07-11 02:19 UTC
Gregtech newhorizons 2.0.4.6
on the prospercraft online server

after updating to this 'more stable version', the gt++ centrifuge and electrolizer show no signs of life, none of the 'large centrifuge' or 'large electrolizer'  NEI recipes appear to work in either machine.

the GT++ ore washer and macerator stack work perfectly.

**Comment by Prewf** [comment] 2018-07-11 03:04
which version of gt++ are you running?

**Comment by whalas** [comment] 2018-07-11 03:20
1.7.1.01-fresh is the official version in the mods main class file

**Comment by Prewf** [comment] 2018-07-11 03:32
1.7.2.0-fresh fixed most of the recipes i think. there was a recipe (rubber wood) that still didn't work on that version, but it should've since been fixed in 1.7.2.2-fresh

refer to https://github.com/GTNewHorizons/NewHorizons/issues/3216

**Comment by whalas** [comment] 2018-07-11 03:33
neat, i'll let the server admin know :) thanks

**Comment by draknyte1** [comment] 2018-07-11 04:06
Be aware that the versions @Prewf is referring to isn't available for public use, as it's only available to my Beta testers. But the issue is resolved and should be fixed next GTNH update~

**Closed** 2018-08-06 14:31 UTC
Labels: FixedInDev, need to be tested
