### ISSUE TITLE
Forestry core block wrong quest requirements

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3923] opened 2018-12-18 20:37 UTC
#### Which modpack version are you using?
2.0.6.2
The quest Forestry core block #557 has the wrong item casing requirement.

**Comment by richardhendricks** [comment] 2018-12-19 07:19
Unless it has been fixed already, looks right to me?

![2018-12-19_01 18 49](https://user-images.githubusercontent.com/1214811/50204947-21ade680-032c-11e9-83e8-a511a3f7c8dc.png)
![2018-12-19_01 19 21](https://user-images.githubusercontent.com/1214811/50204948-21ade680-032c-11e9-943a-1bd1fafa288f.png)

**Comment by Dream-Master** [comment] 2018-12-19 08:10
no it has to be gt casings

**Comment by Dream-Master** [comment] 2018-12-20 14:45
![image](https://user-images.githubusercontent.com/2970688/50291201-36929300-046e-11e9-9a4c-f792f7ca4537.png)
![image](https://user-images.githubusercontent.com/2970688/50291211-3d210a80-046e-11e9-8f92-559a470c67fd.png)
all was oredicted

**Comment by ko5h** [comment] 2018-12-20 15:59
imho its quest "Forestry core block" №577
duplicate of #3920

**Comment by Dream-Master** [comment] 2018-12-20 19:05
ah ok

**Closed** 2018-12-20 19:05 UTC
Labels: can't reproduce
