### ISSUE TITLE
Basic Miner mine Bedrock

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#2650] opened 2018-02-27 17:20 UTC
Bedrock is mined a little. Perhaps Bedrock he was on the way to the resource or in the drill path.

#### Which modpack version are you using?
2.0.2.7

**Comment by Dream-Master** [comment] 2018-02-27 17:25
@code32 can you show us a pic ?
@richardhendricks any idea on this ?

**Comment by code32** [comment] 2018-02-27 17:47
I found Bedrock in the chest near the Basic Miner. That's all I know, all the rest is hypothesis.

**Comment by code32** [comment] 2018-02-27 18:11
@Dream-Master 
![2018-02-27_21 09 48](https://user-images.githubusercontent.com/3153076/36746162-a6a9912a-1c02-11e8-98bd-0b6c4832aab5.png)
![2018-02-27_21 09 58](https://user-images.githubusercontent.com/3153076/36746167-a9ef041e-1c02-11e8-846f-efe1a9581a7b.png)

**Comment by Dream-Master** [comment] 2018-02-27 19:42
@mitchej123 any idea?

**Comment by mitchej123** [comment] 2018-02-27 23:18
Will take a look - would be great if someone had detailed steps on how to reproduce the bug so I can reproduce it locally.

**Comment by bartimaeusnek** [comment] 2018-02-27 23:35
If i remember it right, this happens when a water srping is in the range of the miner...

**Comment by Dream-Master** [comment] 2018-02-28 08:01
Ok then it is not real bedrock it is the spring have bedrock texture.

**Comment by eloquentJane** [comment] 2018-02-28 13:57
Presumably a fix for this would be to blacklist the water springs from the miner's list of mineable blocks (assuming that's possible).

**Comment by Dream-Master** [comment] 2018-02-28 15:26
i guess we did this allready

**Comment by code32** [comment] 2018-03-03 09:31
The Nether
![2018-03-03_12 29 57](https://user-images.githubusercontent.com/3153076/36932742-cf7d4a7c-1ede-11e8-8e12-79049c355579.png)
![2018-03-03_12 30 09](https://user-images.githubusercontent.com/3153076/36932743-cf99a8fc-1ede-11e8-8fa4-fd689200dbdb.png)

**Comment by Dream-Master** [comment] 2018-03-03 09:56
@code32 is there a hole in the bedrock floor ?

**Comment by code32** [comment] 2018-03-03 10:10
@Dream-Master No
![2018-03-03_13 07 01](https://user-images.githubusercontent.com/3153076/36933057-2798e428-1ee4-11e8-9b80-7a673cc23ca9.png)
![2018-03-03_13 09 06](https://user-images.githubusercontent.com/3153076/36933058-27b5671a-1ee4-11e8-86b0-183aae02d3f2.png)

**Comment by Dream-Master** [comment] 2018-03-03 10:11
not sure if there is a lava spring as well.

**Comment by code32** [comment] 2018-03-03 10:39
![2018-03-03_13 36 49](https://user-images.githubusercontent.com/3153076/36933326-25fdf4c4-1ee8-11e8-9325-6f75da90d4f1.png)
![2018-03-03_13 38 57](https://user-images.githubusercontent.com/3153076/36933339-441b530c-1ee8-11e8-8744-1b1f0cab45b9.png)
![2018-03-03_13 37 22](https://user-images.githubusercontent.com/3153076/36933343-4c0db550-1ee8-11e8-9618-9713fb4dfefd.png)

**Comment by code32** [comment] 2018-03-03 10:49
@Dream-Master The automatic drill stops production based on the height. The problem would have been solved had the automatic drill stopped its work by touching Bedrock.

**Comment by Dream-Master** [comment] 2018-03-04 07:53
@mitchej123 @richardhendricks @Technus @codewarrior0  @bartimaeusnek any idea how to change it in code?

**Comment by codewarrior0** [comment] 2018-03-04 08:03
It looks like the miner does a hardness check on the block below the mining pipe tip, but uses the wrong coordinates. Should be an easy fix.

**Comment by Dream-Master** [comment] 2018-03-04 08:41
ok

**Comment by codewarrior0** [comment] 2018-03-04 09:56
https://github.com/GTNewHorizons/GT5-Unofficial/pull/106

**Closed** 2018-03-10 09:59 UTC
Labels: FixedInDev, need to be tested
