### ISSUE TITLE
Missing recipe (Soduim Persulfate via Chem reactor)

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/NewHorizons#2653] opened 2018-02-28 14:50 UTC
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Soduim Persulfate quest asks to be made in a chemical reactor, but the recipe is missing in NEI.

I suggest changing the quest to make people follow the alternative route (that uses Sodium Bisulfate Dust)

**Comment by Dream-Master** [comment] 2018-02-28 15:26
I guess this is fixed allready. Will check.

**Comment by mtesseracttech** [comment] 2018-03-01 20:23
@Dream-Master You can close this one, it's a duplicate of #2509 and #2545

**Closed** 2018-03-01 20:32 UTC
