### ISSUE TITLE
GT item name error when scanning with Stockroom Catalog.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5641] opened 2020-02-23 15:28 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Scanned the inventory in the Stockroom Catalog and opened Stockroom Catalog
#
#### What happened instead? (Attach screenshots if needed)
GT item name is wrong.
![2020-02-24_00 15 53](https://user-images.githubusercontent.com/40425798/75114804-9ac96c00-569c-11ea-9cb4-ea71f5b7bc84.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by boubou19** [comment] 2020-02-23 15:33
duplicate of #5571 and #4828

**Comment by Dream-Master** [comment] 2020-02-23 15:35
@yukieiji i close this now. Feel free post under the original issue. Thanks

**Closed by Dream-Master** 2020-02-23 15:35 UTC
Labels: duplicate
