### ISSUE TITLE
circuit / pcb crafting issue

### ISSUE THREAD

**Issue by thcv** [GTNewHorizons/NewHorizons#2586] opened 2018-02-09 21:32 UTC
#### Which modpack version are you using? 2.0.2.7

#
#### If in multiplayer; On which server does this happen? Prospercraft

#
#### What did you try to do, and what did you expect to happen? Cannot craft 4157.  The circuit required for it cannot be crafted either, the recipe for it is trumped by a Steve's cart pcb recipe.

#
#### What happend instead? (Attach screenshots if needed)

https://i.imgur.com/oYSx3e2.png

https://i.imgur.com/sLLOnIO.png

#

**Comment by Dream-Master** [comment] 2018-02-09 22:25
yes will add a circuit to pcb chip

**Comment by thcv** [comment] 2018-02-09 22:27
Can 4157 be changed to accept any MV circuit?  Feels like it would suit progression.

**Comment by Dream-Master** [comment] 2018-02-09 22:31
4157 ?

**Comment by thcv** [comment] 2018-02-09 22:32
IC2 advanced circuit

**Comment by Dream-Master** [comment] 2018-02-09 22:45
can make it oredict if that not is oredicted

**Comment by thcv** [comment] 2018-02-09 22:50
That would be sweet, thanks.  Seems silly to have to backpedal to make IC2 specific circuits when you are already HV tier.

**Comment by Bluebine** [comment] 2018-02-10 00:13
The PCB uses basic circuit boards, the integrated circuit uses good ones.

No need for any change, there's no recipe conflict.

And the advanced circuits use the integrated circuits because the other MV circuits are way cheaper and easier to make, as well as being lower-tech.

**Comment by Kortako** [comment] 2018-02-10 00:21
I don't really understand what the issue is.  Are you saying the ID for 4157 is the IC2 Advanced Circuit?  Item IDs are different for pretty much every server/game instance in 1.7.10, so just saying that doesn't really help.

You certainly can craft the IC2 Advanced Circuit, you just have to go through making Integrated Logic Circuits and Good Integrated Logic Circuits, which are different from the normal Electronic Circuits and Good ECs an MV player on the cusp of HV would probably have been making up until that point.  I've took that to just be the way the progression is.  Oredicting ILC to also accept EC would skip over that completely.

Your screenshots aren't very clear either, you say the GC is trumped by a Steve's Cart's PCB recipe, but that PCB recipe you show needs a completely different type of Plastic Board, so I don't think they conflict.  Can you explain a little more?

**Comment by thcv** [comment] 2018-02-10 00:29
The basic / good board mix up was my mistake, sorry, this pack is pushing my mental capacity.

When I asked if the IC2 advanced circuit could accept any MV circuit, what I meant to ask is if it could accept an integrated processor (cleanroom), rather than just a 'good integrated circuit'.

**Comment by Kortako** [comment] 2018-02-10 00:32
Oh, I see.  In theory, any quest or crafting recipe should  be able to accept a Processor Assembly, not be forced to use an IC2 Advanced Circuit.  If that's the case, it's the recipe itself that is bugged, not the process of creating an HV IC2 circuit, and that is what should be oredicted/fixed.  That has already been fixed in the past for several HV quests/crafting recipes.  What are you trying to make that specifically requires the IC2 advanced circuits?

**Comment by thcv** [comment] 2018-02-10 00:34
Jetpack quest requires one even though the recipe does not, I guess I was supposed to make it before the cleanroom?

**Comment by Kortako** [comment] 2018-02-10 00:37
Oh, then @Dream-Master should oredict that quest so that it accepts Processor Assemblies too. The nanosuit quest was already fixed before, it used to be the same way.

**Comment by thcv** [comment] 2018-02-10 00:54
Thanks for your help, sorry for the confusion.

So to clarify: 
1) The IC2 advanced circuit recipe should be changed to also accept processor assemblies, rather than only 'good' circuits.
2) The jetpack quest needs to be fixed so that processor assemblies are acceptable in place of IC2 advanced circuits.

**Comment by Kortako** [comment] 2018-02-10 01:02
#2, yes, #1, not quite.  Processor assemblies (HV tier) are equivalent to the IC2 advanced circuit, and can be made through the clean room using Good Integrated Processors.  By the time you reach HV, you should make the IC2 advanced circuit version maybe once or twice, and upgrade your clean room to be able to make the "better" HV circuit, which is the Processor Assembly.  The motivation to do so is that, well, IC2 advanced circuits are a pain to make, forcing to you make LV -> MV -> HV chips, where as Processor assemblies start off at MV -> HV.   So basically what I'm saying is, if you can make MV circuits in the cleanroom, then you should be close to making HV circuits in the clean room as well, and then this whole issue won't be a problem.

**Comment by codewarrior0** [comment] 2018-02-10 01:02
Er, it's by design that you can't use the Integrated Processor to craft the IC2 Advanced Circuit. Circuit upgrading is divided into tiers, such that you cannot upgrade a circuit more than three times along that tier, nor can you build primitive circuits using more advanced components.

I'd only recommend changing quest requirements and pack-specific recipes and not changing the core GT circuit progression.

**Comment by thcv** [comment] 2018-02-10 01:07
Thanks for the explanation.

**Comment by Dream-Master** [comment] 2018-02-10 10:49
I add only control circuits to crafting

**Comment by Dream-Master** [comment] 2018-02-10 10:51
The jetpack circuits allready ordictet

**Closed** 2018-03-10 09:59 UTC
Labels: FixedInDev
