### ISSUE TITLE
weird behavior of super buffers

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3151] opened 2018-06-18 21:32 UTC
#### Which modpack version are you using?
delta one
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
trying to output tiny piles 9 by 9 in a input bus for packaging purpose, expected things to work as planned.
#
#### What happend instead? (Attach screenshots if needed)
here is the setup:
![sb4](https://user-images.githubusercontent.com/12850933/41562845-22803c2a-734e-11e8-9dee-1639d7559a67.png)
for the 1st experience the buffer is set to output tiny piles 9 by 9 inside the block at his right (an EV input bus) and for the 2nd experience the buffer is set to output tinypiles 18 by 18 inside the compressed chest.

result of the first experience:
![sb2](https://user-images.githubusercontent.com/12850933/41562933-66aecd58-734e-11e8-9bce-e9671e656ba2.png)
if you count the piles, you'll see that this is not a multiple of 9, plus only the last slot have 9 tiny piles( not like in the 2nd experience described below) and it's not adding a single more tiny pile so it will definitively stuck the multiblock after a while.

result of the second experience:
i got the slots of my chest full of 18 piles (this is good)
![sb3](https://user-images.githubusercontent.com/12850933/41563095-e27b5d66-734e-11e8-8bc8-43332e2a501e.png)
but if i take some items to simulate an extraction of item (let's say a conveyor or an item conduit)
![sb2](https://user-images.githubusercontent.com/12850933/41563301-8f82dca0-734f-11e8-9dda-ffdab8b7a4fb.png)

it will refill automatically the slot to 18, even if the slot isn't empty, transforming the multiple of 18 into a non multiple. (not good)
![sb3](https://user-images.githubusercontent.com/12850933/41563095-e27b5d66-734e-11e8-8bc8-43332e2a501e.png)

plus if i add a non multiple of 18 manually, it will do nothing to complete to a multiple of 18 so there is an inconsistancy with its behavior.

I hope i described the problem correctly, feel free to ask more details and i'll do what i can to complete this description.

**Comment by richardhendricks** [comment] 2018-06-19 07:21
I see in your 1st and 3rd picture there is a pile with only 13 items, right under the tooltip.  Is that the bug, or from your testing?

**Comment by richardhendricks** [comment] 2018-06-19 07:36
Super buffers do not immediately push if the destination inventory has room.  They follow this algorithm.

Once every 200 ticks (10s), try to push. 
If successful, keep pushing every tick and reset counter to 50.
For the first 6 ticks after a successful push, push every tick (each success resets counter to 50)
If 6 ticks didn't push, push every 5 ticks until 50 ticks have passed.

So if you pull out a destination item in an inventory, it may take up to 10s before the superbuffer attempts to push out more items.

If the inventory in the superbuffer has been modified by another block adding items, or if it has successfully pushed items out, it resorts and combines inventory stacks.

So if you pull out some items from the target inventory, you may have to wait up to 10s before the superbuffer will attempt to fill the inventory.

**Comment by boubou19** [comment] 2018-06-19 07:40
that's not the problem i try not point out: the issue is it push an incorrect number in the compressed chest:
for the slot under the tooltip with 13 items, after a delay that you seems to confirm with your algorithm description, it will complete the slot to 18 items, but it don't add 18 more items

**Comment by richardhendricks** [comment] 2018-06-19 13:01
No, that is how the superbuffer/chestbuffer operates.  It keeps the output inventory slots at the level you requested, it does not add that many.  If you ask for 36, and take 1, it replaces the 1.  You need to make sure your consumer uses the amount you are requesting, or a multiple of it.  For example, you can use a packager with tinyDusts schematics at 9, 18, 27, etc. 

If you are using it for both tiny and small dusts, use 36 for the stocking level.

This is exactly like a store - if you buy 1 box of cheese, they put 1 new box of cheese on the shelf.

Also, btw, make sure your receiving inventory is as small/large as necessary.  Using a large receiving inventory will cause unnecessary lag since the superbuffer has to compare every one of its inventory slots against every receiving inventory slot.

**Comment by richardhendricks** [comment] 2018-06-19 15:15
The problem there is that the input bus has its own logic for handling its inventory.  Try this on an EBF input slot, spread a bunch of iron dust or whatever across the slots, and it will compress them into one slot. 

That is input bus behavior, nothing to do with the super buffer.  If you want the input bus to work properly, I recommend using a 1 slot input bus, or filling all but one slot with junk.

This does sound like a potential problem with the multiblock packager.  I'll notify @draknyte1.

**Comment by boubou19** [comment] 2018-06-19 16:44
well it happened also inside an input bus of a processing array with 64 packagers so i don't think it's specifically linked to the amazon warehouse.

**Comment by richardhendricks** [comment] 2018-06-19 20:44
I agree, it's not a warehouse problem, it's an input bus problem.  The input bus is collapsing the stacks.  If you really need to have a specific # of items, use a 1 slot input bus, or fill the rest of the slots with cobble or something else not needed (they will need to be filled all the way) except for one.

You can change the output value to some multiple of what you need instead of just 9, if that works better for your process. 

So, fill all outlet inventory  to 64 cobble except one slot
Set super buffer to keep 63 items in the inventory. (if you need multiple of 9, for example).

For lag prevention/reduction, use the smallest input bus you can.

**Comment by boubou19** [comment] 2018-06-19 20:46
so basically you tell me that in this pack we don't have a fast and stable way to handle tiny piles? that's a serious lack imo

**Comment by richardhendricks** [comment] 2018-06-19 21:01
I am telling you the pack is ***working as intended***.  Just use it according to the limitations I outlined above.  Tiny piles work *just fine* with a GT single block packager.  

If there is an issue with the multiblocks using collapsing input buses, we can try to fix it or suggest alternatives.  We can look at adding a "non-collapsing input bus" type that does not collapse the stacks in its input slots, but that would require pretty extensive testing before any release so systems you design now should work around the issue until then.

Or we can try adding a new mode to the superbuffer to change from "stocking" mode to "minimum transfer size" mode.

How fast does the Amazon warehouse or PA with 64 packagers go?

**Comment by boubou19** [comment] 2018-06-19 21:06
Amazon warehouse or PA with 64 packagers are so fast that they check if they are items in buses faster than the items go inside the bus, so if i use ulv input bus it's useless to use an amazon warehouse or a PA full of packagers. What would be helpful in my opinion is to add a mode for super buffers that consists in adding exactly the amount you set to output, not completing the slots inside the output. With that all issues will be solved.

**Comment by richardhendricks** [comment] 2018-06-19 22:14
Yes, that is my "minimum transfer size" mode I gave above.  We can discuss if this is a better mode to use vs stocking.

I don't see a real problem with it myself, since you can still have it transfer 4/8/9/etc items at a time as long as their is space in the destination.  But it would require development and confirmation that it won't be an issue etc.

**Comment by richardhendricks** [comment] 2018-06-19 22:35
(notes for dev)
GT_Container_ChestBuffer.java
GT_Container_SuperBuffer.java
controls GUI slot behavior.  Maybe we can add a new slot that does (stocking mode/transfer size mode)

GT_GUIContainer_ChestBuffer
GT_GUIContainer_SuperBuffer
These contain info on the actual GUI itself, in case we decide to add a new slot.

GT_MetaTileEntity_ChestBuffer stores actual code for algorithms etc.
GT_MetaTileEntity_SuperBuffer is just subclass of above with different max parameters.

With new behavior

```
    protected void moveItems(IGregTechTileEntity aBaseMetaTileEntity, long aTimer) {
        int tCost = GT_Utility.moveOneItemStack(aBaseMetaTileEntity, aBaseMetaTileEntity.getTileEntityAtSide(aBaseMetaTileEntity.getBackFacing()), aBaseMetaTileEntity.getBackFacing(), aBaseMetaTileEntity.getFrontFacing(), null, false, mTargetStackSize == 0 ? 64 : (byte) mTargetStackSize, mTargetStackSize == 0 ? 1 : (byte) mTargetStackSize, (byte) 64, (byte) 1);
        if (tCost > 0 || aBaseMetaTileEntity.hasInventoryBeenModified()) {
            mSuccess = 50;
            aBaseMetaTileEntity.decreaseStoredEnergyUnits(Math.abs(tCost), true);
        }
    }

```

change the call to 
```
    public static byte moveOneItemStack(Object aTileEntity1, Object aTileEntity2, byte aGrabFrom, byte aPutTo, List<ItemStack> aFilter, boolean aInvertFilter, byte aMaxTargetStackSize, byte aMinTargetStackSize, byte aMaxMoveAtOnce, byte aMinMoveAtOnce) {
```
Make it update the min/max move at once to the user-config mTargetStackSize and use 64/1 for max/min target stack size

**Comment by richardhendricks** [comment] 2018-06-20 04:30
Transfer size mode will keep transferring as long as the destination inventory has space to receive that size. Example with 2 slots, and setting to 9 items:
Stocking mode:
9,9 -> no more items added.
Transfer mode
63,63 -> no more items added.

The second mode is useful for input hatches that collapse things. For example
Stocking mode:
9,9 -> hatch collapses to 18,0 -> 18,9 -> 27,9 -> 36,9 -> 45,9 -> 54,9 -> 63,9 -> hatch collapses to 64,8 -> 64,9  (notice how now there is not a mutliple of 9 items any more)
Transfer mode:
9,9 -> hatch collapses to 18,0 -> 18,9 -> 27,9 -> 36,9 -> 45,9 -> 54,9 -> 63,9 -> hatch collapses to 64,8 -> 64,17 -> 64,26 etcetc to 64,62 (still multiple of 9)

**Comment by richardhendricks** [comment] 2018-06-20 06:02
OK I have something working.  It transfers multiples of the configured amount.  IE, set to 9, it will transfer 63x4 items into this LV input hatch and stop.  Now, this means if you pull a stack, it won't count how many are in there and will still get messed up, but if the recipe is pulling a multiple, the chest/superbuffer will now push a multiple.
![2018-06-20_00 59 53](https://user-images.githubusercontent.com/1214811/41639949-885ed9f2-7425-11e8-8633-3bc477a7604e.png)

Need to do some cleanup on the GUI I guess i did my math wrong, it is putting the active area in the wrong spot.
![2018-06-20_01 02 45](https://user-images.githubusercontent.com/1214811/41639977-a6694a90-7425-11e8-9b2e-c749338d5db3.png)

**Comment by richardhendricks** [comment] 2018-06-20 06:05
Super buffer behaves the same, set to 20 items per transfer output

![2018-06-20_01 05 21](https://user-images.githubusercontent.com/1214811/41640082-0d558688-7426-11e8-812a-b0c22bb9bdf4.png)
![2018-06-20_01 05 50](https://user-images.githubusercontent.com/1214811/41640089-132edaaa-7426-11e8-9648-34f22c321752.png)

**Comment by richardhendricks** [comment] 2018-06-20 07:13
@boubou19  Please test this GT version in SSP game and see if the behavior is acceptable.
[gregtech-5.09.32.28.zip](https://github.com/GTNewHorizons/NewHorizons/files/2118239/gregtech-5.09.32.28.zip)

**Closed** 2018-06-20 07:53 UTC
Labels: Need Code changes, bugMinor, need help

**Comment by boubou19** [comment] 2018-06-20 20:31
all good :D
