### ISSUE TITLE
Galena on moon

### ISSUE THREAD

**Issue by Dr4cos** [GTNewHorizons/NewHorizons#2151] opened 2017-10-30 17:12 UTC
#### Which modpack version are you using?
2.0.1.3 (Thanks Oliverxll) ^^
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
The Galena ore on moon seems to be not harvestable via pickaxe/hammer  but shovel don't know if this  is the intention, also the chalcopyrit is hard as hell there xD

#
#### What happend instead? (Attach screenshots if needed)
![fehler](https://user-images.githubusercontent.com/33230359/32184734-7286bd28-bd9d-11e7-945a-9559def8ed33.png)
#
#### What do you suggest instead/what changes do you propose?
Pickaxe/hammer if this is a error ^^

**Comment by ko5h** [comment] 2017-10-30 18:59
Duplicate of #2059

**Comment by Oliverxll** [comment] 2017-10-30 22:05
MyFTB doesn't use 2.0.1.1, it uses 2.0.1.3*
See you there Dr4cos ;)

**Comment by Dream-Master** [comment] 2017-10-31 15:39
This is indeed wired. @richardhendricks  any idea?

**Comment by Dream-Master** [comment] 2017-12-01 05:37
![image](https://user-images.githubusercontent.com/2970688/33469252-f7a0f71c-d661-11e7-82fe-f031df79124c.png)
![image](https://user-images.githubusercontent.com/2970688/33469254-fc92b904-d661-11e7-85ed-8e5a3c501347.png)
I placed a ore beside the wrong generated one. Not sure what happend here @richardhendricks ?

**Comment by richardhendricks** [comment] 2017-12-12 03:06
I don't think this will fix already-placed ores, but should fix any new ore placement.

**Closed** 2017-12-14 11:44 UTC
Labels: FixedInDev, need to be tested
