### ISSUE TITLE
Chest buffers causing significant TPS drop

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#2919] opened 2018-05-11 04:57 UTC
#### Which modpack version are you using?
2.0.2.7

#
#### If in multiplayer; On which server does this happen? 
Prospercraft

#
#### Whats the problem?
An admin on our server was running a profile and found chest buffers and the super buffers cause a significant drop in TPS when they're operating. It went from using a tick time of 0.011 when idle to 2.5 when it is pending to move items.
Could cause significant issues on larger, more progressed servers.

**Comment by Dream-Master** [comment] 2018-05-11 07:01
will asking if this is a problen on my server too,

**Comment by 0lafe** [comment] 2018-05-11 07:07
I remember we had some errors with it on dirthuts, and it seemed like it had something wrong, but apparently it wasn't causing lag. I did once have mine almost freeze the server because I had some ic2 plutonium in it, and it was outputting to a packager. 

Don't think they ever impacted server play much other than that though.

**Comment by Namikon** [comment] 2018-05-11 09:28
Can agree with that.
We had (have) the same issues; They are caused by Recipe-Table lookups when using Autopackages/Autocrafting tables that do 4x4 / 9x9 patterns for dust processing.
Make sure people do use the correct packager shape to compress dusts; There is a dust shape especially for that.

**Comment by Dream-Master** [comment] 2018-05-11 09:30
can we do code wise something @Namikon ?

**Comment by Namikon** [comment] 2018-05-11 09:36
Dunno. Since we have that quest which points people to the Dust-Shape for the packager, those problems have almost disappeared on our Servers. Just remembered we had such issues.

**Comment by Dream-Master** [comment] 2018-05-11 09:39
ok good so solved ? or did we need to add some tooltip ? @Namikon

**Comment by Namikon** [comment] 2018-05-11 11:18
I'd ask @AlexBucket if this describes his problem or not. I was just remembering a comparable issue we had

**Comment by AlexBucket** [comment] 2018-05-11 11:59
I had 2 in my area in different chunks. One was automated having saplings and apples pushed into a regular MV chest buffer with an output setting of 8 into a compressor making plantballs, and my other was a MV super buffer that I would dump all my tiny piles into when they started to clog up my ME system, and would have an output setting of 9 pushing into a packager with a dust pattern.

**Comment by Bryfer** [comment] 2018-05-11 14:00
how many apples/saplings do you need to storage anyway?
I belive this issue could be related to the chest buffer having a HUGE numbers of items inside it, and therefore causing these TPS drops.
I'd recommend you to use an barrel/drawer with voiding filter instead of the chest buffer when dealing with apples/saplings
The dust part you described is more common and should not cause problems. but it really depends on how much dusts you put into it from time to time or if its automated?

**Comment by AlexBucket** [comment] 2018-05-11 15:12
Doesn't matter if there is a few stacks or no stacks of dusts, when it starts processing to output, the TPS jumps.

The apple/sapling thing was to automate outputting the correct amount into a compressor so it doesn't jam up with 1 sapling and then won't allow anything else into it. I'm doing it for plantballs -> fermented biomass. I'm just using them how they're designed to be used, but theres a TPS issue there.

It shouldn't have to do with a 'HUGE number of items inside it'. The MV chest buffer holds 27 stacks of items only. It's the same size as a normal chest.

**Comment by Bryfer** [comment] 2018-05-11 15:23
Please correct me if I'm wrong here
The chest buffer can hold 27 Different items
The super chest buffer can hold 256 Different items
There is an really high or unlimited storage for each kind of items it can hold

**Comment by AlexBucket** [comment] 2018-05-11 15:52
I'm not 100% on the super buffer because it requires a data orb to read,  but the regular chest buffer only holds 27 stacks of 64 items. And the tick jump isn't relevant to the amount of items in it. Weather it be half full or nearly empty, when it goes to do a process the TPS spikes significantly

**Comment by 0lafe** [comment] 2018-05-11 17:28
Pretty sure the super buffers hold 16384 items

**Comment by Cinobi** [comment] 2018-05-27 19:36
![2018-05-27_22 25 57](https://user-images.githubusercontent.com/25028786/40589896-57b040fe-61fe-11e8-9ac0-7c717217453c.png)
Live epsi server.

**Comment by richardhendricks** [comment] 2018-06-02 08:31
Should be resolved by https://github.com/GTNewHorizons/GT5-Unofficial/pull/124

**Closed** 2018-06-14 19:39 UTC
Labels: FixedInDev, Lag, bugMajor, need to be tested
