### ISSUE TITLE
Duplication of quest requirements in Stone Age (Tier 0.5)

### ISSUE THREAD

**Issue by Arynnia** [GTNewHorizons/NewHorizons#5780] opened 2020-03-20 22:21 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Was browsing quest book to prepare for video. Did not have a particular plan.
#
#### What happened instead? (Attach screenshots if needed)
Discovered that main quest "Important tools" and side quest "Got a flat tire?" both require players to craft a crowbar, duplicating effort.
#
#### What do you suggest instead/what changes do you propose?
Would recommend eliminating one of the crowbar quests to avoid duplication of effort.

**Comment by wlhlm** [comment] 2020-03-21 08:43
Duplicate of #5407

**Closed by wlhlm** 2020-03-21 08:43 UTC
Labels: duplicate
