### ISSUE TITLE
Assembly line automation

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2564] opened 2018-02-05 14:36 UTC
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
We have so many ways to make assembly lines craft things automaticly(not a sarcasm, i know three atleast), and the only thing that stop me for being completly happy is low capasity of data hatch.

Data hatch is genios thing itself, but have only 16 slots. We have 52 ass line recipe right now, so need 4 asslines to autocraft everything. Why not to chage this?

Possible ways:
1. Add more slots to data hatch
Proc: Easy to maintain, 
Cons: Damages GT item buses system. If the pack will recive more assline recipes - this will need more ass lines again
2. Allow the ass line to support more data hatches than 1.
Proc: 256 total slots(with 16 data hatches) for recipes, do not need to ruin the GT item system
Cons: little harder to maintaince
3. Add "input-output" mechanic support to data hatch(allowing to insert or extract items to it with other blocks like EIO pipes
Proc: do not need to change the multiblock itself
Cons: may couse different diffictles with timing it automate things.

**Comment by Dream-Master** [comment] 2018-02-05 14:46
I am with you @Cinobi But I can't programm it myself since I fail the last time with the 32 slot input hatch.

**Comment by repo-alt** [comment] 2018-02-05 17:55
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/2437 ?

**Comment by Dream-Master** [comment] 2018-02-13 10:40
![image](https://user-images.githubusercontent.com/2970688/36145788-b945d90c-10b2-11e8-968c-b279f1f9a829.png)

**Closed** 2018-03-10 09:59 UTC
Labels: FixedInDev
