### ISSUE TITLE
Talisman of Nourishment recipe doesn't work

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#1545] opened 2017-06-21 17:18 UTC
As in the tittle, the infusion recipie for Talisman of Nourishment doesn't work at all.

**Comment by Dream-Master** [comment] 2017-06-21 17:23
can you make some pics for me? @mulisz100

**Comment by mulisz100** [comment] 2017-06-21 17:34
![2017-06-21_19 30 05](https://user-images.githubusercontent.com/27481104/27397958-6a3e997a-56b8-11e7-9bd7-08a6aede6820.png)
![2017-06-21_19 30 24](https://user-images.githubusercontent.com/27481104/27397962-6df2c046-56b8-11e7-92e9-b469f33e55f4.png)
Research is done, every required item and essentia is placed in appropriate places and hitting Matrix with wand doesn't do anything.

**Comment by Dream-Master** [comment] 2017-06-21 17:36
did you try whith a false ruby maybe i did it wrong. There are two rubys. @mulisz100

**Comment by Dream-Master** [comment] 2017-06-21 17:42
is fixed allready was false rube before.

**Comment by Bryfer** [comment] 2017-06-21 19:34
Dupe of #1338

**Closed** 2017-06-25 15:11 UTC
Labels: duplicate, FixedInDev
