### ISSUE TITLE
Name of SuperChest is disabled

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5389] opened 2020-01-19 07:51 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
My server
#
#### What happened instead? (Attach screenshots if needed)
Name of SuperChest is "SuperChest (Tier) [Disabled]"
Disabled but could be made and used.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment] 2020-01-19 10:00
You want a name tier tag on each chest ? @yukieiji

**Comment by yukieiji** [comment] 2020-01-19 11:56
Yes.
"[Disabled]" after the name of "SuperChest Ⅰ" ~" SuperChest V"
![2020-01-19_20 55 43](https://user-images.githubusercontent.com/40425798/72680523-1b290a00-3afe-11ea-82ae-94e0deebda81.png)

**Comment by chochem** [comment] 2020-01-19 12:40
Duplicate of #5227

**Comment by Dream-Master** [comment] 2020-01-19 12:50
wait are they from gt5u or from gt++. I remember there are two variants

**Comment by yukieiji** [comment] 2020-01-19 12:56
@Dream-Master Is this? #4812

**Closed** 2020-01-19 14:14 UTC
Labels: duplicate
