### ISSUE TITLE
Gadomancy Core issue (and potential fix)

### ISSUE THREAD

**Issue by GoldBlockIngot** [GTNewHorizons/NewHorizons#4321] opened 2019-03-28 17:15 UTC
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Tried creating a gadomancy aura core attuned to Ordo using the construct recipe. It should have created the core at the cost of a crystal cluster.
#
#### What happend instead? (Attach screenshots if needed)
Upon clicking the core, an explosion sounded and there was a clientside crash.
#
#### What do you suggest instead/what changes do you propose?
I have heard the issue has something to do with conflictions with Blood Arsenal, if this can't be fixed using code I would suggest a new recipe, my suggestion would be in the Arcane Crafting Table, with the blank core, an crystal cluster of your choice and 85 vis of that same element, or 25 of each element in the case of the mixed core.

**Comment by bartimaeusnek** [comment] 2019-04-02 05:46
should be fixed with https://github.com/GTNewHorizons/BloodArsenal/pull/2 , also duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/3502

**Closed by bartimaeusnek** 2019-04-02 05:46 UTC
Labels: duplicate
