### ISSUE TITLE
Assembling machine bug

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1134] opened 2017-02-22 21:32 UTC
This bug has happened to all three of my assembling machines. It lets me craft 1 thing (cable/coil/etc) and then once it goes to the second it permanantly out of power. If i use a battery, still goes 90% then reset. If i connect a wire/batt buff to it does the same.

**Comment by Dream-Master** [comment] 2017-02-22 22:01
@kokochicken Make a video for me. I am 100% sure this is not a bug you are using the machine wrong.

**Comment by Technus** [comment] 2017-02-26 11:29
Need more info, ss with chunk alignment etc.

**Comment by Dream-Master** [comment] 2017-03-05 13:40
@kokochicken We need more info.

**Comment by Dream-Master** [comment] 2017-03-07 13:56
@kokochicken i close this if we not get more infos.

**Closed** 2017-03-10 21:35 UTC
Labels: Need more Infos, question
