### ISSUE TITLE
Void fortress infusion does not work

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/NewHorizons#2889] opened 2018-04-30 20:04 UTC
#### Which modpack version are you using?
My log says that it is "GTNewHorizonsCoreMod-1.7.10-1.5.18"

#
#### If in multiplayer; On which server does this happen? 
private server, singleplayer also
#
#### What did you try to do, and what did you expect to happen?
Infusion from Maleficia tab - void fortress armor. I triet helmet and leggins, did not try chestplate

#
#### What happend instead? (Attach screenshots if needed)
Nothing happened when clicked runic matrix with wand, like there was no such recepie.

#
#### What do you suggest instead/what changes do you propose?
some fix )

**Comment by bartimaeusnek** [comment] 2018-04-30 22:05
post the log please.

**Comment by Dream-Master** [comment] 2018-05-01 02:35
![image](https://user-images.githubusercontent.com/2970688/39459031-ee6d4bb8-4d22-11e8-868f-f7672267ded9.png)

**Comment by Dream-Master** [comment] 2018-05-01 02:43
![image](https://user-images.githubusercontent.com/2970688/39459103-4eaab89e-4d23-11e8-9e1a-9405141a90f6.png)
![image](https://user-images.githubusercontent.com/2970688/39459212-135ab7c0-4d24-11e8-8014-d1c6f0dcca33.png)
sorry but cant reproduce works fine for me

**Comment by Dream-Master** [comment] 2018-05-01 03:31
@monroth

**Comment by bartimaeusnek** [comment] 2018-05-09 16:45
since he didnt report back ill close this. @monroth feel free to reopen this if you report back.

**Closed by bartimaeusnek** 2018-05-09 16:45 UTC
Labels: Need more Infos, can't reproduce
