### ISSUE TITLE
Bee quest: Alvearies #1123

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#3486] opened 2018-08-19 08:41 UTC
#### Which modpack version are you using?
2.0.4.6
#
The items required in the quest are more than is needed.
1728 wood logs are needed in the quest, however this number is only correct if an impregnated casing requires 64 wood logs, however they only need 8, my guess is that the maths came to 1728 assuming you needed 216 casings instead of just 27 (as you needed 216 scented panelling). which brings the maths of it to only needing 216 wood logs. The same issue applies to the amount of seed oil required, as you only need 6750L of seed oil for 27 casings, not 54000L.

So it is as follows:

Wrong numbers:
1728 wood logs
54 seed oil Cells

correct numbers:
216 wood logs
6.75 seed oil cells

Suggested requirement:
216 wood logs
7 seed oil cells (rounded up)

**Comment by Bryfer** [comment] 2018-08-19 08:50
dupe of #3291

**Comment by Dream-Master** [comment] 2018-08-20 19:34
![image](https://user-images.githubusercontent.com/2970688/44362265-c0325400-a4c0-11e8-99c1-6cd8db3eb570.png)
fixed long time allready.

**Closed** 2018-08-26 16:08 UTC
Labels: FixedInDev, duplicate
