### ISSUE TITLE
Strange ore behaviour

### ISSUE THREAD

**Issue by Gemlord** [GTNewHorizons/NewHorizons#2059] opened 2017-10-07 16:17 UTC
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 
Dirthuts
#
#### What did you try to do, and what did you expect to happen?
Mine Some ore on the moon, specficially chalcopyrite, galena and Molybendite
#
#### What happened instead? (Attach screenshots if needed)
the ores variously think they need a shovel to mine, have hardness 8, and a huge variety of completely wrong properties, i have no idea what could cause this,
![image](https://user-images.githubusercontent.com/18751509/31309724-f27c1fdc-ab82-11e7-94c0-6de6b7037932.png)
![image](https://user-images.githubusercontent.com/18751509/31309727-fec14812-ab82-11e7-814d-35430534d67a.png)
Most bizzarely of all they still actually mine with a hammer and pick as they should, but as if it's an

**Comment by Dream-Master** [comment] 2017-10-07 17:08
very strange.

**Comment by Bryfer** [comment] 2017-10-09 15:50
@Dream-Master 
> @Toperoco @ko5h its better to disable the mining level in waila ?

Waila is really useful to have. dont disable it.

try to figure out why waila is reading alot of ores wrongly instead of disabling it.

**Comment by Dream-Master** [comment] 2017-10-09 17:37
Sure need help with this.

**Comment by SirAzazel** [comment] 2017-10-10 07:03
This is duplicate of old report of WAILA Harvestability: squeek502/WailaHarvestability#52
Also this is just a continuation of incorrect tool for some blocks such as wires or pipes.

**Comment by Dream-Master** [comment] 2017-10-10 08:07
This info bring us not closer to a solution?!

**Comment by Bryfer** [comment] 2017-10-10 13:43
@SirAzazel Im not sure if that report is really what is happening here considering the ores was working fine prior to updating. something most likely was changed incorrectly when updating recently.

**Comment by Dream-Master** [comment] 2017-10-10 15:50
Will test in sp maybe a server client config mismatch idk

**Comment by Toperoco** [comment] 2017-10-10 19:39
The ores can actually be mined with a shovel and drop properly, which leads me to believe that this is not, or at least not only an issue with WAILA

**Comment by Dream-Master** [comment] 2017-10-10 21:07
@Toperoco What ores can you list some you can harvest with a shovel?
Thanks

**Comment by Toperoco** [comment] 2017-10-10 23:51
Every vein I encountered on the moon has at least one of these. All in all there are more shovel ores than there are pickaxe ores, e.g. the whole titanium vein mix, galena, lead and chalcopyrite.

**Comment by Dream-Master** [comment] 2017-12-01 12:11
@richardhendricks

**Comment by richardhendricks** [comment] 2017-12-06 07:08
I did some basic research.

Q on meta data.  I am trying to understand why Galena and Lead ores require a shovel, but Garnet/Cassiterite sands do not.
Based on my guessing, 
 
```
    public String getHarvestTool(int aMeta) {
        return aMeta < 8 ? "pickaxe" : "shovel";
    }
```
(edited)
uses the lowest byte of the aMetaItemSubID, which makes sense for
```
    public static Materials Galena                  = new Materials( 830, 
    public static Materials Lead                    = new Materials(  89, 
    public static Materials Silver                  = new Materials(  54, 
```
since 830 & 0xFF = 14,   89 & 0xFF = 9,    54 & 0xFF = 6.  Which matches GT scanner in-game
But using GT scanner on garnet SAND and Cassiterite SAND(which should use a shovel) returns a metaData of 1.  They are
```
    public static Materials CassiteriteSand         = new Materials( 937, 
    public static Materials GarnetSand              = new Materials( 938, 
```

which should be 9 and 10, if it really is the LSB.

@Dream-Master Was any kind of tweak done to make Cassiterite Sand and Garnet Sand use a pick instead of a shovel?

**Comment by richardhendricks** [comment] 2017-12-06 07:20
Does Galena/Lead in Twilight Forest behave this way?  It could be a problem with GalacticGreg ore spawning vs Overworld ore spawning.

**Comment by richardhendricks** [comment] 2017-12-06 08:42
Galena/Lead/Silver in TF does not behave like this, all 3 are pickaxe harvesting.

lead meta = 1
silver = 2
galena = 3

I just don't understand where these numbers are coming from.


My best guess is that GG is placing ores the "correct" way, and that it is actually the GT setOreBlock that is causing problems with the meta data.  Don't really have the slightest idea why though.
I don't understand how the lowest nibble of metadata can be the harvest tool, yet in setOreBlock, values are adjust by 1000/2000/3000/4000 etc when placing ores in nether etc, that doesn't screw up the harvest tool metadata.  Those values should cause it to shift by 8. :thinking:
My best guess is that the aMetaData there is not the same metadata used by the getHarvestTool function, but ???? is beyond me.,

**Comment by richardhendricks** [comment] 2017-12-12 03:10
![2017-12-11_21 08 02](https://user-images.githubusercontent.com/1214811/33865506-ae016ff2-deb7-11e7-9fa2-e34f6ba9e3e1.png)
![2017-12-11_21 08 27](https://user-images.githubusercontent.com/1214811/33865507-ae1550c6-deb7-11e7-9b6e-1677b6ecfce6.png)
![2017-12-11_21 08 35](https://user-images.githubusercontent.com/1214811/33865508-ae2abc0e-deb7-11e7-972b-203a45333854.png)
![2017-12-11_21 09 52](https://user-images.githubusercontent.com/1214811/33865509-ae38a210-deb7-11e7-8fb9-35ef6bb9560d.png)

**Closed** 2018-06-05 18:10 UTC
Labels: Need more Infos, bugMinor, help wanted
