### ISSUE TITLE
Electrolyzers process water instantly

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2018] opened 2017-09-26 18:54 UTC
It looks like electrolyzers process water at 20 operations per tick, while using the same amount of EU/t. Players have reported that this behaviour changes, sometimes going back to the regular 100s per operation. Same thing happens in processing arrays and is not affected by power source (generator/battery). Tested with LV and MV electrolyzer with no notable difference.

(v2.0.0.0 - DirtHuts server)

![electrolyzer](https://user-images.githubusercontent.com/11035501/30877842-424f8fe8-a2fb-11e7-8623-1b15ea5b3643.gif)

**Comment by Dream-Master** [comment] 2017-09-27 21:37
I add a circuit to the recipes. distilled water was nerver displayed in the recipes.

**Comment by Dream-Master** [comment] 2017-09-27 22:02
Works now fine.

**Comment by Dream-Master** [comment] 2017-09-27 22:04
![image](https://user-images.githubusercontent.com/2970688/30940148-56e3ae4a-a3e0-11e7-934d-eb3996606818.png)

**Comment by MineAnPlay** [comment] 2017-09-28 04:03
No, don't add circuit. The issue isn't that. It's because of GT++ but should be fixed next version.

**Comment by Dream-Master** [comment] 2017-09-28 08:57
@MineAnPlay distilled water was never shown in nei  but as recipe in code. After the circuit addition change you can see both and use recipe.

And btw i tested it with the new gt++ version.

**Comment by MineAnPlay** [comment] 2017-09-28 13:41
There is NOTHING about distilled water here... The issue is with the GT++ Multiblocks. It was also fixed(https://github.com/draknyte1/GTplusplus/commit/413652508f003ebfd8190ec4a8da3453ea7a4e26)

**Comment by Dream-Master** [comment] 2017-09-28 14:39
@MineAnPlay In gt code there was a hidden recipe with distilled water. Thtas why i add circuits. That alkalus fixed the issue is good.

**Comment by Dream-Master** [comment] 2017-09-28 14:39
```
GT_Values.RA.addElectrolyzerRecipe(GT_Values.NI, ItemList.Cell_Empty.get(1L, new Object[0]), Materials.Water.getFluid(3000L), Materials.Hydrogen.getGas(2000L), GT_OreDictUnificator.get(OrePrefixes.cell, Materials.Oxygen, 1L), GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Values.NI, null, 2000, 30);

GT_Values.RA.addElectrolyzerRecipe(GT_Values.NI, ItemList.Cell_Empty.get(1L, new Object[0]), GT_ModHandler.getDistilledWater(3000L), Materials.Hydrogen.getGas(2000L), GT_OreDictUnificator.get(OrePrefixes.cell, Materials.Oxygen, 1L), GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Values.NI, null, 2000, 30);
```

**Comment by MineAnPlay** [comment] 2017-09-28 16:18
Yes but you don't need to add a circuit to that recipe and why would anyone use Distilled Water to make Oxygen/Hydrogen...

**Comment by Dream-Master** [comment] 2017-09-28 16:59
Why not. Large boiler gives distilled water back. If I not locked in code I never know such recipe exists . I let the circuits in.  Maybe gt++ add some recipe in the future with similar engridienst and then we have the problem again.

**Comment by MineAnPlay** [comment] 2017-09-28 19:44
Water is made a LOT easier and for free unlike making Distilled Water. If one wants Hydrogen they WILL use an infinite water source. They will use Distilled Water for other recipes/machines, not to electrolyze it. So there is no reason for this.

**Comment by Dream-Master** [comment] 2017-09-28 20:00
Its vanilla code i add only circuit.

**Comment by MineAnPlay** [comment] 2017-09-29 16:15
Please just revert it. There is NO reason. The recipes WON'T conflict and NO one will use Distilled Water to make Hydrogen. If something works with NO problems do the first rule. Don't change it!

**Comment by Dream-Master** [comment] 2017-09-29 16:27
Why you don't like to tell me strait what is the problem. I am really want to understand why you think the change is bad. Ok I understand no one will use distilled water and I will remove this recipe but why remove the circuits I not sure about the reason.

**Closed** 2017-10-08 11:13 UTC
Labels: FixedInDev
