### ISSUE TITLE
Liquid dupe with Extracells ME Liquid storage bus and Extrautilities drum

### ISSUE THREAD

**Issue by VasyaOrk** [GTNewHorizons/NewHorizons#4864] opened 2019-07-21 15:16 UTC
Liquid dupe with Extracells ME Liquid storage bus and Extrautilities drum
---

Gregtech New Horizons 2.0.7.5, Singleplayer

I use Extrautilities drum and Extracells ME Liquid storage bus for molten soldering alloy storage.
Molten soldering alloy uses in different circuits recipes via Extracells ME Liquid interface.
Soldering Alloy filled into circuit assembler but do not drain from drum ==> liquid is duped.

When I access via ME Liquid terminal (fill cells) : correctly filled, correctly drained ==> No dupe.
When I use ME Liquid storage cell for storage : correctly filled, correctly drained via terminal and via  ME Liquid interface ==> No dupe.
GT tank : not tested.

This dupe works with all tested types of liquid (12 types).

**Comment by DoomSquirter** [comment] 2019-07-21 15:21
already reported many times.  dupe of #2514

**Closed** 2019-07-21 18:28 UTC
Labels: duplicate

**Comment by Dream-Master** [comment] 2019-07-21 19:02
fixed in dev
