### ISSUE TITLE
Transformers explode when reconfigured twice with the soft mallet.

### ISSUE THREAD

**Issue by NullCascade** [GTNewHorizons/NewHorizons#1466] opened 2017-06-07 08:08 UTC
See image here:
![image](https://user-images.githubusercontent.com/720169/26868425-db9b25a8-4b1d-11e7-9bc4-1e90da36eb39.png)

**Comment by Bryfer** [comment] 2017-06-07 16:01
Not sure what the issue is? When you invert it the lv and mv sides change. Also the mv input becomes an 4x lv input meaning in this case you would feed it mv power into the lv input side?

GT mschines explode if they get mv power if they are lv mschines?

**Comment by Technus** [comment] 2017-06-07 16:25
the issue here is that the soft mallet is somehow async to energy net causing transformer to explode

DO NOT TOGGLE LIVE PARTS

**Comment by Dream-Master** [comment] 2017-06-07 21:01
so i guess we can close it? @NullCascade @Bryfer @Technus

**Closed** 2017-06-25 15:15 UTC
Labels: question
