### ISSUE TITLE
don't update gt++ going forwards

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#5556] opened 2020-02-09 22:42 UTC
As we all know, gt++ will be obfuscated, with mappings changing every version, going forward. Now, you guys can choose whichever path you want here, but I would give it some thought as to whether you want to ever be able to change anything at all (for example, if one wanted to add some other radon production system to replace the current ones) without wading through func_219380_a() and having it break every version.

**Comment by draknyte1** [comment] 2020-02-09 22:45
Obfuscated for 2 reasons, which all parties involved are fine with.
My mod isn't up for discussion on how it works or what it does, this has *always* been the case and I don't know why anyoe thinks they deserve anything else.

**Comment by quedral** [comment] 2020-02-09 22:48
I don't see that happening since gt++ itself adds tons of new stuff and fixes few (and somtimes breaks) stuff on every update. however if you want to change recipes like radon  production system you can choose not to update in your personal pack imo.

**Comment by sthegreat** [comment] 2020-02-09 23:20
Changing things is exactly the difference between a proper modpack and a zip with a bunch of mod jars in it, and I imagine gtnh wants to be the former. Consider that rotarycraft was removed from gtnh for pretty much exactly this reason...

**Comment by GTNH-Colen** [comment] 2020-02-09 23:47
GT++ is broken af in the current version used by GTNH; see https://github.com/GTNewHorizons/NewHorizons/issues/5423.

**Comment by 0lafe** [comment] 2020-02-10 00:26
>My mod isn't up for discussion on how it works or what it does, this has always been the case and I don't know why anyone thinks they deserve anything else.

I like how when it comes to witchery it's like, maybe we remove it bc we can't change it. But when it heavily fucks with the main mod of the pack, it's completely ok to not be able to edit it lol.

**Comment by draknyte1** [comment] 2020-02-10 00:28
Witchery can be changed 100%, thanks to my efforts (And Bart's on the brewing side of things), it won't be going anywhere at all.

See, Dead mods that aren't being actively worked on or dead mods needing fixes aren't on the same level as a mod in active development. That's why they get ASM'd, that's why they *potentially* could be removed (Albeit Witchery would break a heap of things if it were, so awfully doubtful anyway)

**Comment by Rongmario** [comment] 2020-02-10 03:10
100% agree with this issue title.

**Comment by repo-alt** [comment] 2020-02-10 14:24
Theoretically it would not be the end if the world if we throw out GT++ for good, after all it was completely broken on the official servers probably longer than it was working. And single player users may drop it in manually, if they wish.

**Comment by GTNH-Colen** [comment] 2020-02-10 16:13
> Theoretically it would not be the end if the world if we throw out GT++ for good, after all it was completely broken on the official servers probably longer than it was working. And single player users may drop it in manually, if they wish.

Wouldn't this completely corrupt virtually everyones save files though?

**Comment by repo-alt** [comment] 2020-02-10 19:26
Not sure about that, should be tested.

**Comment by xTwi** [comment] 2020-02-10 20:10
Disagree with issue title, GT++ adds a good amount of stuff that was missing from normal GT such as maceration multi and the single block boilers which in normal GT for some reason fell off after steam age among other things. It's a healthy addition to the pack imho.

**Comment by Anarack** [comment] 2020-02-11 03:12
throwing everyone that has made a power substation or has heavy gt++ infrastructure back to the stone age is a completely viable idea with no issues at all let alone anyone that has heavily invested in gt++. 

If can't implement a change safely in a mod pack with 6+ min months of play time your idea is wrong.

**Comment by chochem** [comment] 2020-02-11 07:34
disagree with the title as well. gt++ adds tons of great stuff that is well integrated into the pack. Bugs, while there have been a fair few, are removed pretty quickly overall. While I can not speak for the officials which maybe used badly broken versions of gt++, it remains very easy to drop the latest version into you sp or local server to fix any problems.

I just hope that the GT++ mods and GTNH devs find a good understanding so that the mod can still be adjusted a bit for the pack where needed. (e.g. centrifuge bonus output could be a config option)

**Comment by GTNH-Colen** [comment] 2020-02-11 10:10
95% sure this isn't a divisive issue, the majority of the community wants to keep GT++ as has been demonstrated again and again. You can add as many laughing reacts as you want to peoples comments it doesn't change this, put the vote up on discord and see what happens.

**Comment by ScriptedPiky** [comment] 2020-02-11 11:01
As many have already stated, removing GT++ would require a significant amount of work to ensure that literally, every single world does not crash, corrupt, or otherwise make their saves (including servers) unplayable. Creating a new mod that replaces everything in GT++ is theoretically possible, but again, requires significant amounts of work and extraordinarily testing to be 100% sure. In addition, you will need to ensure that all the same ASM from GT++ is done similarily because many things may or may not work as you would normally see some of them in action. We should think of the players first before anything else.

Now assuming that by the gods & the stars aligning, we get a functional replacement to GT++ that doesn't crash or corrupt worlds and functions similarly to same mod, then it's all happy flowers & daisies, at least what we'd assume.

In my opinion, I do enjoy some of the multiblocks and concepts as they make my life way less tedious, however, a lot of the unfinished content and some of the unbalanced versions of said multi's leaves me on a conflicted side note.

But ultimately, we cannot touch or modify it directly, we cannot remove it due to corruption issues, we cannot easily replace it & tell anyone who has built ANYTHING GT++ related to 'fuck off' and send them back into the stone-age, losing months of progress due to a hasty dumb bootleg replacement unless it is dealt with the utmost caution. We can only hope for the best that somehow everything works fine and dandy in the future.

**Comment by GeicowithaBango** [comment] 2020-02-11 11:08
you can dismantle everything real quick and delete it etc. that isn’t really a problem. did anyone tried to just remove gt++ without having any content in his/her world? i cant think about sth that gt++ would corrupt if you dont have anything to begin with. so does gt++ adds any sort of important code?

**Comment by draknyte1** [comment] 2020-02-11 11:15
Things I ASM:
![image](https://user-images.githubusercontent.com/3060479/74231719-20254780-4cbf-11ea-9e4e-c21ce99f2548.png)

> But ultimately, we cannot touch or modify it directly  

You don't need to, being the real point I keep conveying. @Dream-Master can & does ask for changes and I don't recall a time where I flat out said no.

> centrifuge bonus output could be a config option  

No such thing. The Sifter and Maceration stack have a bonus, however there's functionality within my API for people (Other modders/Devs) to nullify any multi behaviour for specific recipes. (You can add in a 'circuit 23' type item and say that for multiblock X or all, have no speed bonus, or no parallel.)

> I just hope that the GT++ mods and GTNH devs find a good understanding  

If they want things done, they ask & I do it. This has always been the case and I don't know why this would change.

> Wouldn't this completely corrupt virtually everyones save files though?  

YMMV but probably.

**Comment by Connor-Colenso** [comment] 2020-02-11 17:06
> you can dismantle everything real quick and delete it etc. that isn’t really a problem. did anyone tried to just remove gt++ without having any content in his/her world? i cant think about sth that gt++ would corrupt if you dont have anything to begin with. so does gt++ adds any sort of important code?

Really? This comment is insanely disingenuous at best, while yes you could go around your base and break all your GT++ multi-blocks in a few hours how on earth would you process anything after? I was left in a pretty bad spot after the update because only the mixer broke, if they all went I’d be sent back multiple tiers at best. 

It would require an enormous amount of time to essentially completely restructure my base as to exclude GT++ and I don’t think I’m alone in this. Not to mention the fact I wouldn’t even have power without the PSS which basically everyone bar a few anti GT++ cultists uses in their base these days.

**Comment by GeicowithaBango** [comment] 2020-02-11 18:07
well, i would make new infrastructure and then tear down the old one, if that would be the case. seeing your base for instance, doesnt let me think that wrenching everything down would take long a period. neither giving ae the order to autocraft everything you need. my comments here is about corrupting the world. btw, i don’t understand your complaint when the issue is here to not just update ++ anymore.

**Comment by 0lafe** [comment] 2020-02-11 21:29
Idk man, going from 1.4 to 2.0, I went from UV to late HV, needing to make things like epoxy/rubbers/plastics then setup all the circuit lines from pre nano up to crystals. Needed a cleanroom and everything I had to fill it with. Needed the whole new oil line, which destroyed my old setup completely. All of that really wasn't that bad at all, and provided us with a much much better set of recipes/mechanics for everything involved. 

No matter what, if something OP exists, and people use it, people will be upset when it gets taken away. At this point I've learned that's just part of the game. Shit changes, you kinda gotta change with it. Rip to naphtha from oil, but also things like HOG and epoxy are super great additions, and I'm glad I had to loose that much progress for them to exist.

**Comment by botn365** [comment] 2020-02-11 21:32
when you got from 1.4 to 2.0 you got lots of new content to play but removing gt++ would just remove content and reduce choice

**Comment by 0lafe** [comment] 2020-02-11 21:33
Idk if choice is the right word there. Choice implies there's a reason to pick one or the other. It'll remove OPness, which isn't really the same thing

**Comment by GTNH-Colen** [comment] 2020-02-11 21:55
> Idk if choice is the right word there. Choice implies there's a reason to pick one or the other. It'll remove OPness, which isn't really the same thing. Less OP = better game. Also, I'm not entirely sure there wouldn't be something at some point to replace the multis and some of the rest of ++. Something actually meant for NH tho

Removing GT++ would essentially force players to spam PAs? Who actually wants every machine in their base to just be the exact same blue cube for starters? I also have no idea how you've come to the unique conclusion that removing huge swaths of content is somehow not going to decrease the total content available to players? 

How about you go and create a new mod that does what all of GT++ does in a "non-OP" and 0lafe approved way and then come back, should only take you a few hours? Then we can discuss actually removing it and replacing it with that.

Stop beating a dead horse, we're all bored of it.

**Comment by richardhendricks** [comment] 2020-02-11 22:00
All right, this has run its course. Closing.

**Closed by richardhendricks** 2020-02-11 22:00 UTC
Labels: RFC (request for comment)
