### ISSUE TITLE
Quest Item Issue

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#4162] opened 2019-02-27 20:55 UTC
#### Which modpack version are you using?
2.0,5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/37113583/53522195-f1808200-3aea-11e9-9b2a-a19f29badf52.png)
![image](https://user-images.githubusercontent.com/37113583/53522240-ffce9e00-3aea-11e9-83f6-c313ca54518b.png)

#
#### What happend instead? (Attach screenshots if needed)
Quest wants MV superconductor base cable, when for panel u need usual MV superconductor
#

**Comment by Dream-Master** [comment] 2019-02-27 21:46
Solar panel recipes change in 2.0.6.8 so will do a quest update.

**Comment by boubou19** [comment] 2019-02-27 22:19
duplicate of #4123

**Closed** 2019-03-07 21:56 UTC
Labels: duplicate
