### ISSUE TITLE
[Idea] Roto-Rooter: An alternative solution to the plunger

### ISSUE THREAD

**Issue by Snaggerr** [GTNewHorizons/NewHorizons#2790] opened 2018-04-06 00:36 UTC
_I noticed a **somewhat** similar github issue at https://github.com/GTNewHorizons/NewHorizons/issues/2763 that involves liquids and filling up cells in your inventory, but I believe this idea deserves it's own issue because it's quite a bit simpler and to the point, and doesn't really have the same result as this https://github.com/GTNewHorizons/NewHorizons/issues/2763 issue_

Currently there's no way to access liquids located in the input area of any machine without using a plunger and losing the liquid permanently.  I suggest a meta-tool that can be inserted into the item slot of any machine, and it will have a recipe for every single liquid that simply moves it from the input to the output.  I don't think it should be consumed, but perhaps it can have a durability that is decreased with each use.

I'm no programmer, but I believe this would be reasonable enough to implement without changing any of the hard-coded stuff relating to how machine inputs and outputs function.  Just add a ton of recipes for every liquid and every machine that moves it from input to output.

Other ideas could be different tiers (LV, MV, EV, etc) that have faster recipes/can move liquid faster than lower tiers, or Shit-Pumpers/Roto-Rooters could have durabilities based on the metals they're crafted with.

**Comment by draknyte1** [comment] 2018-04-06 04:34
It comes down to code practicality.

Adding a recipe for every fluid (There's alot) to every machine (There's like 50 recipe sets between them?) You'd need to generate all x*50 every start-up, which further increases load time and fills NEI with infinite useless recipes for every machine.

Easiest way I can think of is probably to drop some code into the base machine class that says if slot(x) contains Item(y), move 1000L from from input to output. Some would require special handler because they do not inherit default machine behaviour.
As annoying as it is, the input fluid being 'stuck' is sort of intentional (Doesn't make it great) and the resolution is to use fluid regulators, smaller cells from GT++ (Ask Dream to Re-enable them) or other fluid management routes.

After playing GT5 for years, I can say that it's never an issue with a smart plan or enough LV machines to handle every fluid. But like my disapproval for auto-connecting Pipes/Cables, it turns out that stupidity runs high in the GT community, and people need their hands held for simple things (Like not having cables misconnect and cause explosions).

**Comment by UpstreamEDA** [comment] 2018-04-06 04:40
I hadnt considered that this mechanic is in the game at least partly by design. So be it! Thanks for the informative reply reply, I suppose this issue can now be closed.

**Comment by draknyte1** [comment] 2018-04-06 04:42
Now, no need to close it, I'm not saying your suggestion is bad at all!
Greg made lots of weird design/gameplay choices, doesn't mean they can't be improved.

I was just giving my 2cents.

**Comment by richardhendricks** [comment] 2018-04-09 21:10
I like the idea of this being the powered version of the plunger, with it putting fluids into empty cells one the hotbar, voiding otherwise or if less than 1000B to keep it easy.

**Comment by Dream-Master** [comment] 2018-04-10 00:07
@Technus are you able to add such tool?

**Comment by richardhendricks** [comment] 2018-08-30 15:37
Obviated by the nifty new handpump.

**Closed by richardhendricks** 2018-08-30 15:37 UTC
Labels: Idea, addition
