### ISSUE TITLE
Thermos breaks GT powernet

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3866] opened 2018-11-27 21:13 UTC
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#

Thermos causes several problems with the GT powernet:
- It causes machines to stop when powered over the chunk borders as seen here: #3854 
- It can cause cables that go over the chunk borders to burn due to tickrate differences as seen here:  #3673
- It breaks GT++ decayable dusts

These are actually pretty serious problems, considering that this whole modpack is based around GT power. So unless you want to build your whole base in a single chunk you will run into problems of machines stopping and sometimes your cable will burn for no reason and the resulting fire can cause your machines to explode.

I know this won't be easy, but would it be possible to stop using Thermos on the official GTNH servers? I don't know what plugins are neccesary for you to run the server, but alternatives for /home and /warp should be in ftbutils. I was also told that there is a town plugin in forge and Alkalus offered to port the jobs plugin.

If you decide to stick with Thermos even with its problems, it would be best to inform the players that transmitting power over chunk borders is broken and write a guide on how to transport power over chunk borders with machine hulls or transformers (I don't know if that reliably works. I didn't get around to test it on the official servers yet)

**Comment by 0lafe** [comment] 2018-11-27 21:20
The power issue can be solved with a battery buffer on the end to get machines to not stop, and just using larger cables to not burn them. Unless you're running like 20A+ it's fairly easy to work around. The decaying feature isn't that important considering radon should be changed anyway, or maybe a single block machine that doesn't use power, or like LV or something, to house items as they decay. Not needing a player inventory is a huge plus anyway imo. 

The only big issue I've found with thermos servers is issues with chunks saving. If you tp somewhere, build in it, tp away, then tp back, sometimes it won't have the items you placed and will have rolled back to before you got there. Also issues related with things rolling back only in certain places after restarts. Void worlds seem to make it worse. Someone suggested it was because of some save order, but it's annoying whatever it is. Seems to be related to loading/unloading the area. I think if the place is chunkloaded the loading issues are better, but void worlds still take it hard, especially on restarts. That also could just be the backup plugin the server I played on used, so maybe it's irrelevant.

**Comment by Lainiel** [comment] 2018-11-27 21:36
@0lafe Having a battery buffer for every chunk and running thick cables should probably prevent the machines from stopping, but it can get pretty expensive with higher tier batteries and cables. It still probably won't stop cables from randomly burning from time to time unless you use cables for double the amperage than you actually provide. In my base I like to transform the power one tier up for distribution network and step it down where I need it. I can't build battery buffer one tier up so I'd have to include one battery buffer after every step down transformer.

**Comment by 0lafe** [comment] 2018-11-27 21:49
No, a buffer on the multiblock and cables 2x higher than what you put through works. So only buffers of what tier you're using on the multi. Buffers on each chunk let's you use smaller cables, but like you said, ain't nobody got time for that. I ran all my power across multiple chunks, and never burned a cable/had a multi stop. There were close to 200 non turbine multis, and none ever stopped and no cables burned. Buffering on multis is also just a good idea if your network can draw more than you make, which is a good idea because you don't really use everything all the time, and nobody wants a multi stopping.

**Comment by Lainiel** [comment] 2018-11-27 21:54
Still as I said if you decide to stick with Thermos it would be best to make a page on the wiki acknowledging that Thermos causes issues on the official servers and showing how to design around that so you don't void items in multiblocks or blow up your base on burning cables.

**Comment by Bryfer** [comment] 2018-11-27 22:18
The cable fires was fixed by tec?
Just keep your entire base loaded using anchors all times, and you should not have these problems 
I know I haven't had these issues in forever

And it's very unlikely that nami will change something this major for the official servers

**Comment by 0lafe** [comment] 2018-11-27 23:07
When did he change it? Ive had cables burn, up to 2.0.2.7

**Comment by boubou19** [comment] 2018-11-28 11:41
I can confirm that the glitch happened to me in 2.0.5.1 on delta as well

**Comment by Superlagg** [comment] 2018-11-28 13:14
> How large bases do you guys have?
> Do you have 1 anchor for your 3x3 base
> or multiple anchors, and (3x+)x(3x+)?
> 
> Personally I have 3x3 for mainbase and just some farms, bees etc outside the 3x3. And I've not had any issues with cable fires,
> Only issue I've had is a block/cable sometimes randomly disappeared, even if there is no power at all in the cable
> 
> I would assume cables can still burn if only one of the anchors are loaded and not both?

Problem arises when you use personal anchors and someone other than you wanders by your house. They don't seem to activate the personal anchor (what with them not being you, I think) which causes part of your house to not load properly, allowing this bug to blow out your cables.

I got around it by just connecting everything to EU P2Ps, but there's only so many channels to play with.

**Comment by draknyte1** [comment] 2018-11-28 13:32
Can anyone seriously deny that Thermos *IS* very broken though?

**Comment by richardhendricks** [comment] 2018-11-28 17:08
> Problem arises when you use personal anchors and someone other than you wanders by your house. They don't seem to activate the personal anchor (what with them not being you, I think) which causes part of your house to not load properly, allowing this bug to blow out your cables.

Now that is a new, and interesting tidbit of information I don't think I've heard before.  Kinda obvious in hindsight, but could be a source of problems for people if their base is in an area with frequent visitors.

Is there a global counter for current tick number buried in the world object for Minecraft? We could try to stop the melting by limiting how many ticks off from the source a wire can be before it refuses to send power.  Might still have burning problems or EU flow problems though.

The other solution I can think of is to maintain a list in each wire of the sources that have provided EU through it, and the amp limit of the source.  If it would exceed the amp limit, the wire would refuse the transfer.  It would clear the list at the start of its tick. Ugly, and a little CPU/memory heavy, but should prevent any burning no matter how offset the tick rate is between two chunks.

**Comment by richardhendricks** [comment] 2018-11-28 17:18
Actually, a simple hack might be to just have any wire on a chunk boundary reject more current than it can carry. Takes some "fun" out, but should completely prevent unexpected flaming wires. It would be harder to make it only reject current across the boundary so I'd do just the global rejection.  

Clever players/large bases could take advantage of it I guess, but I think stopping fires/explosions is probably more important. Anyways, if their wire *would* catch fire but didn't, they'd have problems anyways with recipes underpowering.

**Comment by draknyte1** [comment] 2018-11-28 19:36
> Takes some "fun" out, but should completely prevent unexpected flaming wires.

Or just stop justifying using broken server software?

A change like this removes the entire point as to its existence. Wanna be IC2 and pretend?

**Comment by richardhendricks** [comment] 2018-11-28 19:42
Or GTCE?  They removed rain fires. 

I am not in charge of any decisions, just throwing possible ideas out there.

**Closed** 2019-08-30 17:34 UTC
Labels: bugMinor
