### ISSUE TITLE
AE2 can't properly read the inventory of a super/quantum chest.

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/NewHorizons#5098] opened 2019-11-11 22:23 UTC
#### Which modpack version are you using?
GTNH 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
mine
#

#
#### What do you suggest instead/what changes do you propose?
It would be nice if AE2 storage bus could be able to properly read the inventory of a gregtech super/quantum chest, like it does with barrels/drawers

**Comment by repo-alt** [comment] 2019-12-09 02:27
This is relatively easy to do, but I'm not sure where to put that functionality. AE does not have any GT integration, and GT does have AE dependency (optional, for EU P2P), so GT side is more logical. Perhaps gregtech/loaders/postload/something?

**Comment by bigbass1997** [comment] 2019-12-09 03:06
I would expect it to be implemented into existing GT code. Best guess would be directly in [GT_MetaTileEntity_SuperChest](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_SuperChest.java) and [GT_MetaTileEntity_QuantumChest](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_QuantumChest.java), as their superclass has no relevant data.

I'd do it but I don't have any experience with the AE API, so idk exactly how to implement proper support.

**Comment by mitchej123** [comment] 2019-12-09 05:51
I haven't gotten around to finding an example ,but I know some mods do it -- on AE2 for 1.7.10; you need to implement custom amount lookups for querying large  containers.

If someone finds a good example of another mod doing it, it should be pretty easy to add support.

**Comment by bigbass1997** [comment] 2019-12-09 06:10
I'm guessing all you'd need to do is implement an interface from the AE API, but idk which one to use, or if you need to register the class at all (prob. not). But yeah, an example from another mod would help out a lot. Storage Drawers perhaps? or JABBA.

**Comment by Spartak1997** [comment] 2019-12-09 09:00
@mitchej123 @bigbass1997 it's from MineFactoryReload

https://github.com/powercrystals/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/tile/machine/TileEntityDeepStorageUnit.java

**Comment by bigbass1997** [comment] 2019-12-09 09:08
@Spartak1997 What do you mean? I didn't see anyone bring up the DSU. It's been quite a long time since I played with that mod, but iirc the DSU didn't work with AE either. If it really does, can you point out what part of it makes it work?

**Comment by Spartak1997** [comment] 2019-12-09 09:18
If I remember DSU worked fine.
![image](https://user-images.githubusercontent.com/29407630/70423054-fc633c80-1a96-11ea-96e3-a5daab81fa20.png)
![image](https://user-images.githubusercontent.com/29407630/70423127-1735b100-1a97-11ea-9fb7-a37d77a49508.png)

**Comment by bigbass1997** [comment] 2019-12-09 09:19
Oh I know it worked as an inventory, so do the SuperChest and QuantumChest blocks. But when you have more than 1 or 2 stacks, does the AE system read only 1 or 2 stacks, or does it read the real number of items? (say 50,219 for example, or whatever)

**Comment by Spartak1997** [comment] 2019-12-09 09:22
In MFR read real number. GT Chests read only 1 stack

**Comment by Spartak1997** [comment] 2019-12-09 09:22
In MFR read real number. GT Chests read only 1 stack

**Comment by bigbass1997** [comment] 2019-12-09 09:25
Do you know what about the code for the DSU that makes it properly compatible with AE?

**Comment by Spartak1997** [comment] 2019-12-09 09:33
Sorry. I not good in code but I found open source of MFR. Maybe you or mitchel can find code of storage

**Comment by repo-alt** [comment] 2019-12-09 12:59
To support external storage solutions AE2 provides an interface IExternalStorageHandler  which should be registered with AEApi.instance().registries().externalStorage().addExternalStorageInterface

The problem is not in reading the correct number of items (that is done by implementing IMEInventory), but in keeping it updated (which is done by implementing IMEMonitor)
Incorrect IMEMonitor implementation may easily lead to dupes, so it requires some accuracy. There is a helper used in AE integration code for that (MEMonitorIInventory), but it is not in the API.

**Comment by mitchej123** [comment] 2019-12-10 02:39
> To support external storage solutions AE2 provides an interface IExternalStorageHandler which should be registered with AEApi.instance().registries().externalStorage().addExternalStorageInterface
> 
> The problem is not in reading the correct number of items (that is done by implementing IMEInventory), but in keeping it updated (which is done by implementing IMEMonitor)
> Incorrect IMEMonitor implementation may easily lead to dupes, so it requires some accuracy. There is a helper used in AE integration code for that (MEMonitorIInventory), but it is not in the API.

Thanks, I wasn't clear on what to search for when looking for an example.  I'll look around and see what I can do what this info.

**Comment by repo-alt** [comment] 2019-12-20 14:18
@mitchej123 If you are not going to work on that in the near future I may add that integration.

**Comment by 4gname** [comment] 2019-12-20 14:37
@repo-alt pls fix it

**Comment by mitchej123** [comment] 2019-12-20 17:28
I got as far as looking at how it's done (in the ae2 code) for DSU's.. Haven't gone any further than that, so if you have time please feel free @repo-alt   I can point you to what I've found unless you already know where to look.

**Comment by repo-alt** [comment] 2019-12-20 19:05
Ok. Thanks Jason, I think I know where to look. Probably DSU is indeed the example closest to our case, because e.g. Jabba has AE integration just because it has DSU interface. Another example is Better Storage crates, but they seems to be lacking dynamic updates, and Factorization barrels support is one gross hack.

**Comment by repo-alt** [comment] 2019-12-21 03:16
https://github.com/GTNewHorizons/GT5-Unofficial/pull/221

**Comment by repo-alt** [comment] 2019-12-21 03:17
The fact that Quantum and Super chests are 2 identical copies w/o shared logic is sad.

**Comment by 4gname** [comment] 2019-12-21 04:48
@repo-alt thanks
![image](https://user-images.githubusercontent.com/50260829/71303185-ac19a200-23e7-11ea-935f-b5eb52f89360.png)

**Comment by Dream-Master** [comment] 2019-12-21 07:47
@repo-alt thanks for pull. I merged it. Feel free to recode super chest. You know my coding skills are copy paste 😀

**Closed** 2019-12-22 10:49 UTC
Labels: FixedInDev, need to be tested

**Comment by yukieiji** [comment] 2020-07-03 04:42
The output slot of the super/quantum chest isn't readded.
Can it be fixed?

・834 in the terminal.
![2020-07-03_13 36 19](https://user-images.githubusercontent.com/40425798/86432470-cc310300-bd32-11ea-8760-88ed27a938bf.png)
・But in reality, it's 834 + 64
![2020-07-03_13 36 28](https://user-images.githubusercontent.com/40425798/86432476-cf2bf380-bd32-11ea-8f2e-6b7622328997.png)

**Comment by repo-alt** [comment] 2020-07-03 06:00
You can put anything in that slot, and I'm not sure it is accessible via automation.

**Comment by depressed-pho** [comment] 2021-09-29 08:09
Can you please send the patch to the upstream GT5u?

**Comment by repo-alt** [comment] 2021-09-29 08:17
What patch? Also upstream is kinda dead atm, Alkalus was going to take over the support, but left due to lack of time/motivation. It's been more than a year since then.

**Comment by depressed-pho** [comment] 2021-09-29 10:26
> What patch?

I meant this one: https://github.com/GTNewHorizons/GT5-Unofficial/pull/221

> Also upstream is kinda dead atm, Alkalus was going to take over the support, but left due to lack of time/motivation. It's been more than a year since then.

Hmm okay, I still think the proper AE2 support is worth filing an upstream PR so that someday someone can merge it though.
