### ISSUE TITLE
Space Mobs not functioning properly with other mods

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1079] opened 2017-02-03 03:14 UTC
Space Mobs on the moon will ignore the spawn restrictions of a Magnum Torch and spawn within it's range. I've even observed them spawning inside the same room as the torch. It's impossible for them to spawn outside the range of the torch and then walk in range as my moonbase's Hangar is located on pylons 2 meters above the ground, with a Magnum Torch in the middle.
![2017-02-03_15 59 59](https://cloud.githubusercontent.com/assets/10645298/22578192/c87c8d70-ea2b-11e6-89ea-264d0c5a505e.png)

Additionally, on occasion infernal space mobs will have different stats than their names imply. I've encountered numerous mobs capable of using the disabled infernal Disarming skill, and several that use the Ninja, Ghastly and Bulwark abilities without it being part of their name.

**Comment by Dream-Master** [comment] 2017-02-03 07:37
Idk if this is Galacticraft or Gallaxy Space issue together with Extra Utilities(Monster spawn ignore Torch)

All dangerous skills are remuved from Infernal mobs like disarming. If they shuffle the effects i guess Galacticraft and Galaxy Space are cause this issue too.

@Namikon, @Technus  any idea here?

**Comment by Namikon** [comment] 2017-02-03 08:51
Probably caused by the way mobs are spawned initially, or in combination how GC handles the mob-spawning of entities. The torch ignores mob spawns that are explicit set to allow to spawn

**Comment by VermillionX** [comment] 2017-02-03 10:40
I've also encountered Thaumcraft's Crimson Knights (spawned by cultists, not from spawners) also possessing the disarming skill, even though it's not in their name either.

**Comment by Dream-Master** [comment] 2017-03-22 10:24
@VermillionX Try the GT Monster Repellator and report if this works.

**Comment by Dream-Master** [comment] 2017-12-23 14:48
No answer i close this for now.

**Closed by Dream-Master** 2017-12-23 14:48 UTC
Labels: question
