### ISSUE TITLE
Server stops loading at certain point

### ISSUE THREAD

**Issue by MochaDF** [GTNewHorizons/NewHorizons#5091] opened 2019-11-08 21:27 UTC
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Server stops loading at certain point. I accepted the Eula and got official server files so it shouldn't stop loading.
#
#### What happened instead? (Attach screenshots if needed)
Server stops loading at

[23:12:35] [Server thread/INFO] [malisiscore]: Registering VanishingDiamondFrameMessage for Packet with discriminator 3 in channel malisisdoors
#

[fml-server-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/3826282/fml-server-latest.log)

**Comment by bigbass1997** [comment] 2019-11-08 22:10
Have you tried actually logging into the server at this point, to confirm that it hasn't finished loading?

How long did you wait after seeing this message before force closing/terminating the server program?

Have you tried starting over with a fresh download of the server files?

**Comment by MochaDF** [comment] 2019-11-08 22:18
> Have you tried actually logging into the server at this point, to confirm that it hasn't finished loading?
> 
> How long did you wait after seeing this message before force closing/terminating the server program?
> 
> Have you tried starting over with a fresh download of the server files?

I did and I got the normal error for a server being offline.

I launched the server multiple times waiting about 10-20 minutes each

yes

**Comment by Viktor-KN** [comment] 2019-11-08 23:17
I suggest u to replace OpenJDK with Oracle JDK...

**Comment by MochaDF** [comment] 2019-11-08 23:29
umm, I forgot how I set it to OpenJDK in the first place. Do you know how?

**Comment by draknyte1** [comment] 2019-11-08 23:30
> I launched the server multiple times waiting about 10-20 minutes each

Well the issue with this is..
> It only ran for 1:12 according to your log.

First run can take 20mins+ no worry.. Even on a beast of a server on a non-first run, 10-15 minutes start-up times are totally normal. Welcome to GTNH.

**Comment by MochaDF** [comment] 2019-11-08 23:31
that's because that was the latest log where I closed it right away because it kept giving the same error and I decided to make this post

**Comment by draknyte1** [comment] 2019-11-08 23:36
> giving the same error 

Wouldn't that be useful to post then? lol.
Nothing so far indicates anything wrong beyond your lack of patience.

**Comment by MochaDF** [comment] 2019-11-08 23:46
> Nothing so far indicates anything wrong beyond your lack of patience.

I said in the original post that I waited 10-20 minutes multiple times, I just closed it quickly on the last attempt as I decided to make a post and then work on it the next day.

**Comment by bigbass1997** [comment] 2019-11-09 00:18
> 
> 
> I suggest u to replace OpenJDK with Oracle JDK...

@Viktor-KN Using OpenJDK shouldn't be a problem. I've tested the server package using the same Java version as the OP, and it works fine. Though the only difference is the JVM being used. They're using OpenJ9, while I use the hotspot JVM. So perhaps OpenJ9 is incompatible for some strange reason. Idk.

@MochaDF When you get a chance, please boot up the server once again, wait about 20 minutes, then send us the log file at that point; just to be sure there isn't anything missing. Assuming it still fails to get past that point you mentioned, after trying and waiting again, go install the [hotspot OpenJDK version](https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot). Scroll down to the 2nd section for version "jdk8u222-b10", and select the JRE installer for whichever OS you are running. (if you do Java programming, then select the JDK installer instead). It's a long shot imo, but it is worth a try.

If it still doesn't work at that point, then try monitoring your system's resources while the server boots. Maybe your RAM is maxing out without the JVM throwing an error, or some other weird issue with CPU or harddrive I/O. Otherwise I don't know anything else to try without any more clues as to the cause.

**Closed** 2019-11-09 04:05 UTC
