### ISSUE TITLE
[In Planing] GT 3.0 for Mc 1.12 or newer

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3316] opened 2018-07-16 12:18 UTC
This just and RFC idea issue.

what about the idea make GTNH 3.0 for mc 1.12? GTNH 2.0 is done mostly. Only some finishing is needed.

**Comment by WarlordWossman** [comment] 2018-07-16 14:55
The main question is: What do we gain and what do we lose if we move to a more recent version of the game?

And if we are stable on 1.12 has the modding community already moved on to another version?
I heard that it's not that hard to update once you are on the more recent versions tho, even if 1.13 does a lot of technical changes once again.

I think that we are way faster by now compared to when this started around 3,5 years ago, so it would be possible. We have to be aware that a lot has changed with existing mods which means rebalancing things is way more than just applying the same ideas.

In my opinion it's only worth doing this if there is a clear vision on what we want to change and do differently. Copying over nearly the same experience sounds like a waste of time but that doesn't mean we cannot take the concept and expand it further.

**Comment by richardhendricks** [comment] 2018-07-16 15:03
For me I love how the pack incorporates mods into a linear storyline.  I think if we update to a new version that allows us to pull in more adventure/exploration/dimension mods with more bosses etc and create a story beyond vanilla and Twilight Forest.  Does moving to 1.12 allow us to do that? I think we shouldn't start with the tech side, but the exploration/adventure side and see what people would like to do.

**Comment by richardhendricks** [comment] 2018-07-16 15:15
I think that considering issues we've run into before, we need to be really really careful before including closed or limited source mods.  If this GTNH-1.12 sticks around for 4 years, we want to be able to fix stuff when people migrate.

**Comment by bartimaeusnek** [comment] 2018-07-16 15:25
We would loose entire Thaumcraft and Witchery :/

**Comment by WarlordWossman** [comment] 2018-07-16 15:44
I think if anything it would be worked on quite a bit before pushing it to a server in the first place.
As I said when this modpack was first started there was pretty much no playerbase.
If something new happens it hopefully keeps the original GTNH feeling and expands on it, give modded MC more of an industrial feeling. (which needs tons of planning at this point)

**Comment by Zoko061602** [comment] 2018-07-16 15:45
@bartimaeusnek 
Maybe we could use Astral Sorcery and AbyssalCraft.
Astrals Sorcery seems to be quite goog for gating other mods and AbyssalCraft has many Dimensions

**Comment by bartimaeusnek** [comment] 2018-07-16 15:47
Okay, here are some basic guidlines we should follow for optimal Development:

> 1. We don't include Closed Source Mods. If we want them, we shall ask the Devs to give us permission to fork them / give us permission to modify them.
> 2. We don't use Minetweaker, but create a Mod ourselfs, that alter the recipes / add stuff. ( This should be done for performance reasons )
> 3. We should make a Server pre-release and a Client pre-release pack on github so we can controll each other and the release pack has less issures.

Additional ideas:
- Maybe Open GT-NH3 as a new Git Organisation? 
- Make a List of every Mod that needs to be transfered/updated by us and is Open Source.
- Make a List of every Mod that needs to be transfered/updated we use and is Closed Source and therefore need a rewrite from scatch. (To keep basic guidline No. 1)
- Make a List of every Mod that is only aviable in 1.12.2 and might be awesome in our pack.
- Maybe create custom Mods that link the single mods even further together than it's the case now
- Create a hughe Google Sheet on which we can plan things (like which person wants to help where, etc)

**Comment by Krispion** [comment] 2018-07-16 15:52
What do you plan to use for Gregtech on 1.12? GTCE will not be adding most things from 5.09 (complex petrochem, complex circuits, assline and more). A few of their devs seem to hate GTNH as well so I'm not sure it's the best option. There is a WIP addon for GTCE (https://github.com/EmosewaPixel/GregicAdditions) which plans to add a lot of the stuff from 5.09, but it's a one man project from a fairly new dev afaik, so its future is tenuous at best.

**Comment by richardhendricks** [comment] 2018-07-16 15:53
Other planning documents we need

* Power options per tier, and when they phase out
* Materials available per tier, and how they should scale
* Tool materials
* Turbine materials
* Gating for each power tier, where materials should be found

etc

I think for right now a good thing to do would be to experiment with available mods to see what there is on 1.12.  I'd really like to get more interesting dimensions to explore vs more and more GC/GS dimensions with 1 boss and a few interesting ores.  Maybe have the GC/GS ores gate opening a whole new dimension to explore, a la Erebus or other 'fat experience' dimensions.

**Comment by Dream-Master** [comment] 2018-07-16 16:00
thaumcraft 6 is not for 1.12?

**Comment by richardhendricks** [comment] 2018-07-16 16:01
Last I heard, he was targeting 1.10 and will port to 1.12 once it is complete.

**Comment by bartimaeusnek** [comment] 2018-07-16 16:07
@richardhendricks just checked and there is a Beta for 1.12

**Comment by bartimaeusnek** [comment] 2018-07-16 16:20
Also for all that Thaumcraft mods we use, that are OpenSource and that arent going to update (due to various reasons), i think it would be the best to Frankenstein them into one new modular mod we call "GTNH-Thaumcraft-Additions" and port them to 1.12.

**Comment by Zoko061602** [comment] 2018-07-16 16:29
I don't think we need the old TC addons, except maybe thaumic energistics, there are already new ones like Thaumic Additions and Planar Artifice and there are also ports of Thaumic Bases and Thaumic Tinkerer.

**Comment by richardhendricks** [comment] 2018-07-16 16:34
Another thing we need to look at is oreweights.

**Comment by Ugachaga** [comment] 2018-07-16 16:38
I think that you guys greatly overrate the opensource. In the pack there is a whole bunch of open-source mods with dozens, hundreds of unsolved issues. Yes, some critical things like crashes, inter-mods compatibility or performance bottlenecks can be done at the modpack level, but something more will require just huge investments of time and effort. If you really have so much enthusiasm, why we still do not have our own open-source version of Magnum Torch or fixed Infernal Mobs?

In addition, at the moment both 1.12 GTCE and Thaumcraft are in pre-release stage. What is Thaumcraft without addons? What is a stripped-down GT? Too shallow.

My opinion that no need to hurry to jump on 1.12 yet. But I'm with both hands for it if there is a goal to create such complex modpack with deep inter-mod integration on a modern minecraft.

**Comment by Anarack** [comment] 2018-07-16 16:39
Talking about thaumcraft is nice, but first things first we need to get a good hold on what changes we want to make to GT:CE progression, mainly circuits and petro chem, before we even look all that much at anything else. Once we have our core guide and tiers set up we can look at where we want to start access to other mods and or using other mods to gate gregtech progression itself such as lead and nickle in the twilight. Once our main branches of access are set then we look at endgame gating. 

Other things to check
- galactic craft vs advanced rocketry for space junk
- all the different magic mods that are out now
- getting or finding people familiar with the power of new mods to assist in locating them

**Comment by richardhendricks** [comment] 2018-07-16 16:42
Because issues are worked on based on dev interest and priority?  Infernal mobs is on the list, it's just not as high priority as ie fixing party cheats on the coins quest.

And there is a GT repellator that is basically a magnum torch, right?  It does prevent spawns even without power, so it is similar IMO.

**Comment by bartimaeusnek** [comment] 2018-07-16 16:52
> In addition, at the moment both 1.12 GTCE and Thaumcraft are in pre-release stage. What is Thaumcraft without addons? What is a stripped-down GT? Too shallow.
My opinion that no need to hurry to jump on 1.12 yet. But I'm with both hands for it if there is a goal to create such complex modpack with deep inter-mod integration on a modern minecraft.

Agreed.

**Comment by DoomSquirter** [comment] 2018-07-16 16:55
I've played with thaum in 1.12.  it's neat and new features and all but you're missing the bigger picture a bit there.  not only is thaum new-ish for 1.12.  there is literally one addon and it's for the jei integration :)  one of the draws for thaum in gtnh isn't that it's got thaum but literally 2 pages of addons for it as well.

whether or not thaum gets traction like it had on 1.7.10 is totally up in the air.  

getting a pack going and starting the work makes sense but it might be quite a long time till you are feature complete if you're comparing it to 1.7.10 version.  also I think some mods in the works are aiming at 1.13 as target when it comes out.  

HEE 2 is just now getting started in development for example, and chylex is targetting 1.13

**Comment by MineAnPlay** [comment] 2018-07-16 18:05
I love the idea but DO NOT RUSH! Please. We will first outline the idea and determine how the pack will be. Is it gonna be similar to GT:NH but updated to version 1.12.2 or a new modpack with similar integration but not bound by the hardcore recipe rule, but instead focused on adventure, exploration etc. There is many new mods in 1.12.2 that many old possibilities that weren't possible are now possible. But sadly the same is true for the opposite. Many mods won't update and many of those are also closed source so can't be modified either. Another important point that Ugachaga pointed out is that just because we HAVE an open source/permission to fix/edit mods doesn't mean we will do it, because that requires attention and a lot of time especially if we are gonna make new mods that would require creativity which might seem easy but it's hard to find a good concept and idea to implement, even if it's easy. Also one very important thing I would like to add (which bummed me so much when I tried to make a 1.12.2 personal pack) is that Minetweaker can't reload scripts because recipes can't be modified in game because it is loaded earlier now. This will make adding/removing/changing recipes a real chore especially as the pack gets larger and larger. But we also have Game Stages which will give us endless possibilities for quests/progression/gating. So overall it's cool but we need a very large time and attention to invest which for now I'd prefer it to be on GT:NH so that we can polish it as much as possible first.

**Comment by Dream-Master** [comment] 2018-07-16 18:06
@Ugachaga yes no rush. We start 2019 with th project and if we need 4 Years we are done 2023 or later :)

**Comment by Dream-Master** [comment] 2018-07-16 18:08
@MineAnPlay  hopfully we dont need minetweaker and create a mod that load all changed recipes in it.

**Comment by Dream-Master** [comment] 2018-07-16 18:09
We are now more advanced :) Make GTNH great again :)

**Comment by Hakameda** [comment] 2018-07-16 20:44
Tech reborn is an option on 1.12, would need balance added though ofc since it's intended to not be balanced

**Comment by mitchej123** [comment] 2018-07-17 01:09
> I think that you guys greatly overrate the opensource. In the pack there is a whole bunch of open-source mods with dozens, hundreds of unsolved issues. Yes, some critical things like crashes, inter-mods compatibility or performance bottlenecks can be done at the modpack level, but something more will require just huge investments of time and effort. If you really have so much enthusiasm, why we still do not have our own open-source version of Magnum Torch or fixed Infernal Mobs?

What's an example of a critical crash bug that has a stack trace posted & has clear steps to reproduce, and that hasn't been fixed?

> Magnum Torch

 It works, minus the whoopsie from a packaged mod

>Infernal Mobs

What, specifically are you referring to?  Likely priortization.



It's a volunteer project, with open source mods we _can_ fix them if we have time and chose to.   With closed source the only option is ASM hackery.  I personally choose to favor open source mods over closed source mods, as do a lot of the other contributors.

I'd also point out again, it's volunteer, and we fix what is the most critical and what interests us.  If you or others want to start paying for dev time... well I'm sure that would have an impact on prioritization; but I doubt that's going to happen (nor do I think anyone really wants it to) so we'll continue chasing what has the biggest impact or interests us.

**Comment by mitchej123** [comment] 2018-07-17 01:13
> We would loose entire Thaumcraft and Witchery :/

Witchery: Covens which merged with Witchworks: https://minecraft.curseforge.com/projects/bewitchment

Thaumcraft: Uh thaumcraft :). (To be fair... in beta still) Or like astral sorcery, abyssalcraft, etc.


Take a look at sevtech, It did several things well, just missed GT :)


> We don't include Closed Source Mods. If we want them, we shall ask the Devs to give us permission to fork them / give us permission to modify them.

I'm all for asking devs for permission, but I wouldn't go to this extreme.  Significant preference given to open source, but some closed source (or visible but non friendly distribution license) with active dev team open for consideration.

**Comment by bartimaeusnek** [comment] 2018-07-17 01:16
@mitchej123 active dev team is important, but we might want a kind of contract if they move on to newer versions or abbandon the project, that we can continue it. Nothing sucks more than knowing there are issures you simply cant fix without a shitton of reflexion/asm.

**Comment by mitchej123** [comment] 2018-07-17 02:37
@bartimaeusnek I agree; something like that would be ideal.  A fall back license if they abandon it.  Most people seem to be hesitant because they don't want additional support requests, but we're fine to handle those.

**Comment by Vicus-N** [comment] 2018-07-17 08:43
I think, at some point in time you guys should make new game, rather then continue to use minecraft as base...

**Comment by AndrewAmmerlaan** [comment] 2018-07-17 12:30
bartimaeusnek:  

> Additional ideas:

>    Maybe Open GT-NH3 as a new Git Organisation?
    Make a List of every Mod that needs to be transfered/updated by us and is Open Source.
    Make a List of every Mod that needs to be transfered/updated we use and is Closed Source and therefore need a rewrite from scatch. (To keep basic guidline No. 1)
    Make a List of every Mod that is only aviable in 1.12.2 and might be awesome in our pack.
    Maybe create custom Mods that link the single mods even further together than it's the case now
    Create a hughe Google Sheet on which we can plan things (like which person wants to help where, etc)

> EDIT: This is just my personal Opinion on this.

I was bored so I just went ahead and sorted the mods in these lists:

The mods that are both open source and have a 1.12 version available, (aka, the "don't worry too much about these" list)
[List_of_open_source_mods_in_pack_available_for_1.12.txt](https://github.com/GTNewHorizons/NewHorizons/files/2201529/List_of_open_source_mods_in_pack_available_for_1.12.txt)

The mods that are open source but do not (yet) have a 1.12 version, I have indicated the latest available version whenever this version is not 1.7/1.8/1.9 (aka, the "these need to be dropped or forked and ported" list)
[List_of_open_source_mods_in_pack_not_available_for_1.12.txt](https://github.com/GTNewHorizons/NewHorizons/files/2201541/List_of_open_source_mods_in_pack_not_available_for_1.12.txt)

The mods that aren't open source but do have a 1.12 version (aka, the "might be problematic later on" list)
[List_of_closed_source_mods_in_pack_available_for_1.12.txt](https://github.com/GTNewHorizons/NewHorizons/files/2201545/List_of_closed_source_mods_in_pack_available_for_1.12.txt)

The mods that aren't open source and don't have a 1.12 version (aka, the "list of death")
[List_of_closed_source_mods_in_pack_not_available_for_1.12.txt](https://github.com/GTNewHorizons/NewHorizons/files/2201553/List_of_closed_source_mods_in_pack_not_available_for_1.12.txt)

When there was an obvious replacement available I have added this between brackets after the mod. However just because no replacement is indicated doesn't mean there isn't one

I used this [this](https://docs.google.com/spreadsheets/d/1sRroNCV_4JpxrgKNivrOnSi-vz_-TX-a1-ll6WhwBJs/edit#gid=1779156924) spreadsheet as a basis, I hope that it was up to date, If not then the above will contain the most important mods anyway.

**Comment by Dream-Master** [comment] 2018-07-17 12:51
I open up a issue in new 3.0 repo

**Comment by mitchej123** [comment] 2019-08-30 17:36
https://github.com/GTNewHorizons/GTNewHorizons-3.0

**Closed by mitchej123** 2019-08-30 17:36 UTC
Labels: Idea, RFC (request for comment), suggestion
