### ISSUE TITLE
Idiot-proof pumps and drills

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4422] opened 2019-05-07 16:16 UTC
When placing pumps and drills (including multis), emit to player's chat log "Idiots! Place a waypoint at this spot so you don't forget where you placed it."

**Comment by SuperQoop** [comment] 2019-05-07 16:49
Are people really losing them that easily?

**Comment by Hakameda** [comment] 2019-05-07 18:09
Yes, fucking 0lafe lost ours

**Comment by 0lafe** [comment] 2019-05-07 18:28
Hey that was the bag dupe thing

I think

**Comment by Hakameda** [comment] 2019-05-07 18:36
It'd still be in the bag if so I think. Since it's a free ender bag atm

**Comment by draknyte1** [comment] 2019-05-07 18:55
Stupid people should suffer, we can’t nor should we hold their hands for every single thing. 

Duped backpacks are bad, their data is stored externally to the world save. Modify one and both change, this is super useful with a second player because it’s a perfect dupe. Player two can forever remove items placed inside by player one and this isn’t reflected until player one closes the bag. The data file is updated whenever the back closes, so player one closing bag always leaves items intact while player two can infinitely removed them. 

Confirmed this on live servers whenever I got banned.

**Comment by 0lafe** [comment] 2019-05-07 19:06
Does it work the other way? Can player 2 store more and more inside it, and when player 1 opens their bag it deletes everything player 2 added?

**Comment by richardhendricks** [comment] 2019-05-07 20:07
Based upon explanation above, whoever closes their bag second sets the contents, so yeah

**Comment by richardhendricks** [comment] 2019-05-07 20:08
It would be nice though to be able to dupe a bag in case a grave gets screwed up.

**Comment by richardhendricks** [comment] 2019-05-07 20:09
Anyways, as long as we are mocking and making fun of the player, I am ok with holding hands.

**Comment by richardhendricks** [comment] 2019-05-07 20:09
Seeing as I am the source of not 1, but 2 "idiot" toolltips. :D

**Comment by Bluebine** [comment] 2019-05-07 20:14
if you're gonna do a tooltip on the pump, make sure to mention "hey. idiot. cover it from rain."





ask me how i know

**Comment by Hakameda** [comment] 2019-05-07 20:28
The rain thing is a good idea, and it's a wp not exactly hand holding

**Comment by richardhendricks** [comment] 2019-05-08 02:57
These are GT machines, so remember to protect them (and their power sources!) from rain on any side. And set a waypoint with Journeymaps so you don't forget where you placed it!

**Closed** 2019-05-27 18:09 UTC
Labels: FixedInDev, Quest change
