### ISSUE TITLE
stockroom catalogue can't handle item names correctly

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#5571] opened 2020-02-13 20:58 UTC
#### Which modpack version are you using?
live delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to try out the stockroom catalogue
#
#### What happened instead? (Attach screenshots if needed)
for my infinity chest filled with some ingots
![image](https://user-images.githubusercontent.com/12850933/74477322-64753b00-4eab-11ea-893c-bcdabd8024b8.png)

for a random chest
![image](https://user-images.githubusercontent.com/12850933/74477513-b6b65c00-4eab-11ea-82d0-63fda767fa7d.png)
you can notice that forge micro blocks aren't supported either
![image](https://user-images.githubusercontent.com/12850933/74477625-f11ff900-4eab-11ea-8b88-7951b786fe49.png)
(don't know what is the "report error to alkalus" because there is no gt++ item in this chest)

**Comment by repo-alt** [comment] 2020-02-13 21:22
duplicate of ttps://github.com/GTNewHorizons/NewHorizons/issues/4828

**Closed by repo-alt** 2020-02-13 21:22 UTC
