### ISSUE TITLE
(Suggestion) Make creosote worth more in a diesel generator

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1819] opened 2017-08-09 22:28 UTC
As is, creosote is pretty useless in a diesel generator, despite what the quests say. It gives 8000 EU which is incredibly low even by LV standards- burning raw oil gives 16,000 and is easier to get, and diesel itself, while not too hard to mass produce, is worth almost a stack of creosote cells.
I'd suggest 24,000 or 32,000 for creosote, at least.

**Comment by OperativeLoop** [comment] 2017-08-09 22:32
I disagree on this, too easy to mass produce creosote and it would make it less likely people will use other sources. There are also some other ways to get energy from creosote.

**Comment by Bluebine** [comment] 2017-08-09 22:50
At what tier would it be OP? Early LV to MV you've only got standard coke ovens which are very slow, and I found myself only having a few hundred buckets of creosote by the time I'd made my first LV diesel gen, while a single oil deposit, a pump, and a bit of power can supply thousands of oil cells, and with a bunch of power and some water (to electrolyze to hydrogen) you can turn that into thousands of diesel cells with some patience. Once you hit HV and get a pyrolyse oven even diesel gets used up very fast so you'd need ungodly amounts of creosote (I did the math, blast furnacing a stack of stainless steel using creosote-fueled diesel generators, even at 100% efficiency and using oxygen, you'd need 4600 creosote cells, or 18,400 logs in a pyrolyse oven- that's almost 10 chests full of wood, whereas it takes 77 diesel cells to do the same, which isn't at all unreasonable to make by that point) to do very much, and at EV+ I'm sure it'd be even worse due to lowering efficiency and more and more power consumption (not to EV yet so i don't know for sure but i'm assuming)

Also how else do you get energy from creosote?

**Comment by Dream-Master** [comment] 2017-08-09 22:51
Creosote was never desinged for the Disel gen. I can disable it but i wont but it stay at 8.000. Oil have 16.000

**Comment by Dream-Master** [comment] 2017-08-09 22:53
It was used in the smi fluid generators not in diesel gens.

**Comment by OperativeLoop** [comment] 2017-08-09 23:00
Yes, I agree with @Dream-Master , the problem isn't fixed by changing the value of creosote, its fixed by not using creosote at all in diesel generators. 

I believe one of the most efficient ways to turn creosote into power is with a railcraft liquid fueled boiler into steam.

**Comment by WarlordWossman** [comment] 2017-08-14 00:04
And that's a good thing because turning it into steam should be more efficient.

**Closed** 2017-08-14 20:51 UTC
Labels: NO
