### ISSUE TITLE
Wrong items required in quest. #591

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#2788] opened 2018-04-05 18:28 UTC
#### Which modpack version are you using?
2.0.3.0

In forestry and farms quest tree, quest: Multiblock farm: Control block quest requires Emerald electron tubes tubes while control block itself requires Golden electron tubes.

![2018-04-05_20 26 40](https://user-images.githubusercontent.com/9555787/38384566-cdc9c7dc-390f-11e8-92d0-edcd3acce59a.png)
![2018-04-05_20 27 32](https://user-images.githubusercontent.com/9555787/38384567-cde8a418-390f-11e8-9cdc-ffccf31e7fac.png)

**Comment by bartimaeusnek** [comment] 2018-04-05 18:44
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/2722

**Closed by bartimaeusnek** 2018-04-05 18:44 UTC
Labels: FixedInDev, duplicate

**Comment by Dream-Master** [comment] 2018-04-06 00:39
Yea and fixed in dev
