### ISSUE TITLE
GTNH client side option to disable Hardcore Darkness should be eliminated.

### ISSUE THREAD

**Issue by YaNKeeR** [GTNewHorizons/NewHorizons#2649] opened 2018-02-27 01:33 UTC
#### Which modpack version are you using?
GTHN v2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Stone Legion - any for that matter
#
#### What did you try to do, and what did you expect to happen?
There is a client side config for RandomThings that can turn off the hardcore darkness on the client that gives them an unfair advantage when playing on a server that other players are on who suffer the darkness.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
If there is a way to remove the config option to disable it so EVERYONE suffers the night the same way, not some clown who wants to cheat and turns it off locally.

**Comment by noobyaran9** [comment] 2018-02-27 01:34
I suggest adding this mod.
https://minecraft.curseforge.com/projects/hardcore-darkness

But this mod breaks shader which is also one of a way to disable random things hardcore darkness. 

This mods forced the config to be the same as in the server.

**Comment by bartimaeusnek** [comment] 2018-02-27 01:37
tbh i dont see any reason why this is important, especially because you can get nightvision pretty easy...

**Comment by YaNKeeR** [comment] 2018-02-27 01:51
Nightvision is far enough in that you don't get it on night one.  I think removing the config option would be perfect.

**Comment by WarlordWossman** [comment] 2018-02-27 02:00
If you really want to you can still use shaders and I don't think we should remove the ability to use one.

**Comment by Dream-Master** [comment] 2018-02-27 07:18
We don't remove it is part of the pack.

**Comment by TwentyOneZ** [comment] 2018-02-27 11:28
I vote up to using hardcore darkness mod!
Disabling the dark nights effect on client is too easy the way it is now, giving unfair advantage to people who do it in multiplayer servers.

**Comment by Dream-Master** [comment] 2018-02-27 11:39
the problem is i am sure cant use hardcore darkness mod and random things. Is the same mod author and hardcore darkness is a part of the code from random things. I cant proof it the source is close.

**Comment by jiamingc0824** [comment] 2018-02-27 11:46
You can add hardcore darkness mod in if u disable the hardcore darkness from random things configs.

**Comment by Dream-Master** [comment] 2018-02-27 12:13
and this will work ? @jiamingc0824 did you test it ?

**Comment by jiamingc0824** [comment] 2018-02-27 12:15
>and this will work ?

Yes. just make sure u disable hardcore darkness from random things before u add that mod. Also rmb to put a notice about the mod will break shader.

**Comment by Kortako** [comment] 2018-02-27 18:40
I don't like that it breaks shaders. At this point, I feel like you're going to way too much trouble to "ensure" people will keep using hardcore darkness. If people want to change the config, that's their problem. But is it really an "unfair advantage"? Do other people even have advantages over others in this pack? It's PvE in pretty much every way.  And also, keep in mind a lot of people don't even play on the public servers, so this isn't even an "issue" for them.

Basically, if you could find a way to do it without breaking other things, I'd be fine with it. But not like this. That doesn't sit well with me.

**Comment by TwentyOneZ** [comment] 2018-02-27 19:56
> Basically, if you could find a way to do it without breaking other things, I'd be fine with it. 

Hardcore Darkness doesn't stop people from using shaders. I tested it here and it worked fine with ShadersMod v2.3.31 for mc1.7.10, loaded a shader just fine. It says it is 'incompatible' because it doesn't get as dark as the mod's pitch-black nights would get with the shaders - with the shaders you can still see something in the dark, even though it is so much darker than using just the shader.

**You are still able to shaders, so it is not breaking anything.**

**Comment by TwentyOneZ** [comment] 2018-02-27 20:03
> "And also, keep in mind a lot of people don't even play on the public servers"
Thinking about that, single players and custom-server people can even activate the 'moon light phase night lighting' feature that this mod have in single players, which adds a nice balance for those who doesn't like everyday pitch black nights, but also doesn't want it to be that much easier all the time. 
Its a win-win! =)

**Comment by richardhendricks** [comment] 2018-02-27 20:07
Frankly it seems bogus anyways, someone can just hit the F7 key and see where the ground is located using NEI.

**Comment by Dream-Master** [comment] 2018-02-27 20:26
i will close this issue and change nothing. All is fine as it is.

**Closed by Dream-Master** 2018-02-27 20:26 UTC
Labels: question
