### ISSUE TITLE
Mobs need a debuff

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#647] opened 2016-07-28 06:12 UTC
the mobs are at a point where I cant stand them 

these mobs abilities are getting really annoying I understand you want a hard mod pack and stuff but let me tell you the last experience I had so I was in the nether under ground fully safe well I went and found a lil shaft not big are just took a lil skim and left well I came across a rare ( rares are not really rare) mob a hell hound I was like meh run back to my cave and set up a small trap and trapped the hell hound when I tried to kill it I basically killed myself without him hitting me once the effects he gave me from my 3 hits on him was 

poison,   wither,    hunger,    and finally set on fire and I died 

I wasn't to happy these mobs abilities are like so outta hand its tiring like I'm not even nano armor helps and its suppose to help reduce damage taken

even a moderator died to the mob and 2 more rare mobs spawn when he got there,  he had full nano suit tp to the grave to help me get there and seal off the mob well he met a lil surprise from good old spawn mobs that hell hound and 2 skellies (rare) that killed him and he crashed from it and lost his grave it wasn't there,   so if even mods cant kill these mobs how do you expect players that join to even survive trying to gather stuff when you cant even defend yourself

so the final thing is are we suppose to focus on grinding or mobs cause I bet the reason most plays leave is maybe little on grinding and mostly on mobs and there abilities

**Comment by SanMan911** [comment] 2016-07-28 06:52
Okay, so @Dream-Master NOW you would probably know the details of my Discord message to you lol

**Comment by Dream-Master** [comment] 2016-07-28 07:31
Maybe I will change Hellhounds always infernal to random Infernal. This will help find some times seeker Hellhounds.

**Comment by Dream-Master** [comment] 2016-07-28 07:32
Yes and the Nether is the hell :)

**Comment by Dream-Master** [comment] 2016-07-28 08:51
@SanMan911 
No this have nothing to to with #340 . In this issue i adding potions to Mob Drops not let Mobs throw with potions.

**Comment by Dream-Master** [comment] 2016-07-28 08:51
@deathxfighter, @SanMan911  Maybe we have to make a list with Mobs are very hard and need to change.

**Comment by deathxfighter** [comment] 2016-07-28 14:10
dream do you have a list of what all mobs have for aspects?

**Comment by Dream-Master** [comment] 2016-07-28 18:59
sure here the link
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/InfernalMobs.cfg
We can change if Mobs Infernal, alway infernal and the Base health.

**Comment by SanMan911** [comment] 2016-07-28 19:05
@Dream-Master No, I referenced that thread because even @deeplyarnab had suggested something on like lines, such as fishing rod + vengeance = too op. I think we need to think more about disabling certain _aspect combination_ rather than disabling the entire mobs, because doing the latter would make it too easy lol.
Off the top of my head, I think the following combo needs to be disabled:
1. Vengeance + any other [wither/poison/lightning/fire aspect/fishing/hunger. Blindness is fine :D ]
2. Invisibility + fishing/vengeance/wither [Poison, Lightening, Blindness or even Hunger is fine even if it is invisible. Fishing in invisible might make it look like a Hungry node :/ ]
3. Wither + Blindness/Poison/Lightning/Fire Aspect/Hunger [Fishing Rod is still fine for the 'fun' :P]
4. Hunger + Lightening/Fire Aspect [Blindness or Fishing rod is fine]
I mean, in short, having a combination of just two aspects would still be somehow manageable, but not all of them on a mob. Also, I say 'manageable' because if one person is really unlucky, there might spawn 2-3 mobs with all different traits, and the player might still be killed.
Lastly, imho, vengeance is kinda op enough in itself to let it be combined with other aspects, because it is affected by both arrows AND melee hits, so maybe vengeance should be a standalone buff. Many a times you have to attack a boss mob before even you have the time to read its full name because its name is too long as it has so many buffs... And it is only on attacking it or defending yourself that you realize what all aspects it gives you. What might also be interesting, would be to, if possible, add certain good buffs on them, so for example, the mobs may have vengeance on them, but they give you, say, Regen 3 for 10 seconds... something like that... so it's much more fun to kill them bosses :D
Haste, Strength, Night Vision & Regen could be randomly added to the mobs, even if for only, say, 10 or 15 seconds. Just throwing in a possibility ;)

**Comment by SanMan911** [comment] 2016-07-30 14:31
Well, tbh, I don't know whether I should ask for disabling Vengeance, or lifesteal, because lifesteal mobs are literally impossible to kill if you aren't team fighting... You can do a 100 damage to it, it hits you back _just ONCE_ and Wham! It is back at full health again! Basically you either _TRY_ and run away from it, or you just die. You simply can't conquer it.
With the introduction of water creepers, I think this lifesteal mobs could be thought about...

**Comment by WarlordWossman** [comment] 2016-08-03 18:41
One of the biggest problems I have with mobs are passive abilities. If they hit me - fine I will get poison, wither and other effects BUT why would I get those effects when I hit them? It's bad game design imo since I am supposed to be able to fight them but I can't because I get punished for hitting them. 
See? Why would I fight back if I get punished for my own hits on them?
In the end I will just avoid them or bypass direct combat by trapping them and killing them with lava or something. It doesn't make combat harder if you have insane mobs, you will just use other ways to deal with them and that's not what it should be like imo.

**Comment by Dream-Master** [comment] 2016-08-03 19:33
Sure if you can recode the mod i am ok with it. The problem is 1.7.10 are very outdated and no Modauthor will change his mod anymore.

**Comment by WarlordWossman** [comment] 2016-08-03 20:05
Yeah that's sad. But at this point I think the pack would do better without infernal mobs in general because you have to go to the nether a lot earlier now to get sulfur (I know it's a byproduct as well but you need a centrifuge or electrolyser and both of those do require rubber already). I know that you can bypass this with the blue slimeballs since they still give rubber pulp directly but I think you will change that recipe so they will also give raw rubber dust.

**Comment by Dream-Master** [comment] 2016-08-03 20:10
I only remove Infernal mod if i find a better alternative. Maybe small Sulfur can be set to spawn on Dim 0 but this need a map reset.

**Comment by deathxfighter** [comment] 2016-08-15 12:37
idk just nerfing some of the powers and decrease the chance of special/rare mobs would do only a small nerf not a huge one and see how it plays

**Comment by Dream-Master** [comment] 2016-08-26 11:40
Send Nami a Mail waiting for an answer.

**Comment by deathxfighter** [comment] 2016-08-26 11:48
Alright

**Comment by Technus** [comment] 2016-09-12 22:36
https://github.com/GTNewHorizons/NewHorizons/issues/684

Broken combos got broken. Closing.

**Closed** 2016-09-12 22:36 UTC
Labels: suggestion
