### ISSUE TITLE
Add Quest: Basic Electric Oven

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4054] opened 2019-02-02 04:00 UTC
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Add a quest somewhere to have people make a Basic Electric Oven. Maybe good spot is above the Basic Wire Mill?

**Comment by richardhendricks** [comment] 2019-02-02 04:33
Is ti worthwhile for players to spend the time, resources, and EU? The multi smelter is available in MV, which isn't that far away really. If you can come up with a reason, I can add it.

**Comment by MineAnPlay** [comment] 2019-02-02 13:35
Wait, isn't the oven just a retextured furnace? I think you might be confusing it with the microwave?

**Comment by draknyte1** [comment] 2019-02-02 13:57
Ones a furnace and ones a furnace that doesn’t allow metal items as inputs. The one that’s a duplicate of the furnace is even more pointless and exists because of Greg’s ‘example tile entity’ code. It literally is just a retextured furnace that does nothing but exist as an example.

**Comment by MineAnPlay** [comment] 2019-02-02 14:06
That's what I meant. The Electric Oven is nothing more then just a retextured Electric Furnace to look like an oven and the Microwave is a faster and more efficient furnace (4x faster but same eu per tick draw) but only for non metal and non flammable items.

**Comment by Dream-Master** [comment] 2019-02-02 17:10
so is the quest needed or not @shawnbyday ?

**Comment by richardhendricks** [comment] 2019-02-02 17:32
How difficult would it be to make it food items only and say 8x fast and more power efficient.  Would that be interesting at all?

**Comment by MineAnPlay** [comment] 2019-02-02 17:42
No need to, we already have the microwave. Personally I like the texture of the Oven and since it's already in I don't see any reason to change/remove anything. Though you could add an extra comment to the Electric Furnace Quest (if there is one) to also mention the Electric Oven as an aesthetic alternative.

**Comment by shawnbyday** [comment] 2019-02-02 17:44
Oh is there a quest to make the electric furnace already?

**Closed** 2019-02-17 16:14 UTC
Labels: FixedInDev, New Quests
