### ISSUE TITLE
Gendustry Machine Wrong Comb Requirements

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4107] opened 2019-02-17 02:49 UTC
2.0.6.2

The gendustry machines and sub components are looking for the gendustry combs, not the gregtech ones in the crafting recipes.

To fix.

Change the comb the recipes are looking for.

**Comment by Dream-Master** [comment] 2019-02-17 08:43
will check but I am sure this is fixed in 2.0.6.7

**Comment by Dream-Master** [comment] 2019-03-20 09:21
fixed

**Comment by Anarack** [comment] 2019-05-14 19:46
This is not fixed as of 2.0.7.0

**Comment by DietmarKracht** [comment] 2019-05-14 19:47
I can confirm

**Comment by Dream-Master** [comment] 2019-05-14 21:16
fixed in 2.0.7.2 for sure because i remove gendustry combs and they throw out an error otherwise.

**Comment by Dream-Master** [comment] 2019-05-14 21:18
https://github.com/GTNewHorizons/NewHorizons/commit/7be066eada0bd564babc8b24ed40234ed6ea7f8c

**Closed** 2019-05-27 18:10 UTC
Labels: FixedInDev, Need Code changes
