### ISSUE TITLE
Pressing O gives regen

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/NewHorizons#4046] opened 2019-01-29 19:48 UTC
#### Which modpack version are you using?
GTNH 2.0.6.6aDEV
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Toggle Nei with O
#
#### What happend instead? (Attach screenshots if needed)
Gives regen to player, also toggles NEI
#
#### What do you suggest instead/what changes do you propose?
Change the key to unused key
![2019-01-29_14 47 33](https://user-images.githubusercontent.com/4071258/51935873-e3005700-23d4-11e9-8acb-cb5118389db3.png)

**Comment by Lithorn** [comment] 2019-01-29 19:48
Once its started I can't seem to turn it off without relogging

**Comment by Dream-Master** [comment] 2019-01-29 19:52
@Ugachaga any idea about this?

**Comment by Dream-Master** [comment] 2019-01-29 19:52
using 
adventurebackpack-1.7.10-0.9-h10.jar

**Comment by Lithorn** [comment] 2019-01-30 06:12
There is no key to change. None of the keys are related to "Regen". Pressing O just gives me regen, not sure why.

**Comment by Lithorn** [comment] 2019-01-30 06:15
Heres a video https://www.twitch.tv/videos/371919104

**Comment by 0lafe** [comment] 2019-01-30 06:16
I'd guess it has to do with your backpack because of your other status effects. They look like a dragon pack, but I coulda sworn that gave regen2, and it's weird it's not the same time as the others. Do you have a backpack on/which, and any other strange equipment? Could be something you're wearing

**Comment by Lithorn** [comment] 2019-01-30 08:55
Thats what ive been saying. For some reason pressing O force activates the regen

**Comment by Dream-Master** [comment] 2019-01-30 12:09
@Ugachaga thanks for looking into it. Any idea what it is.

**Comment by Ugachaga** [comment] 2019-02-01 02:21
I am out of context now. Need to see which mods have been recently added or updated. Somewhere I can download the latest dev build?

**Comment by Dream-Master** [comment] 2019-02-01 06:57
sure @Ugachaga will send you a link later. Did you have a email adress I can send the link. it's a test pack and not for public rn.

**Comment by MineAnPlay** [comment] 2019-02-01 08:57
What is the oldest version that has this issue?

**Comment by Dream-Master** [comment] 2019-02-01 09:16
I not tested but we can ask on delta or epsilon if this is happend with 2.0.5.1 or maybe someone plays 2.0.6.2

**Comment by MineAnPlay** [comment] 2019-02-01 09:21
Also @Lithorn can you test it on a fresh world? Might be an item/effect that you have that you forgot?

**Comment by Dream-Master** [comment] 2019-02-01 12:14
@Ugachaga you can send me your email adress to dream-master@gmx.net.

**Comment by Lithorn** [comment] 2019-02-03 18:13
Fresh world it dosen't do anything. It is related to the backpack itself. For some reason O is just turning on regen with the dragonpack equiped when its shouldnt. Dragonpack regen kicks in automaticly when player health is lower than max only

**Comment by Ugachaga** [comment] 2019-02-04 05:05
> It is related to the backpack itself.

This is just not possible. Try to get another Dragon Backpack in that world and you'll see the same result. Something in the world corrupt/change some global state when you press O in open inventory. 

The backpack has very simple logic. If we discard possible problems with the server and synchronization, the described behavior means only one thing: the player's current health never reaches its maximum.

> Fresh world it dosen't do anything.

I have not yet been able to run the last dev build, but since the issue cannot be reproduced in arbitrary new world, there is no point in this.

**Comment by richardhendricks** [comment] 2019-02-04 07:43
Lithorn, are you using any health-altering items?  Runic shielding, Tinker's health canisters, ??? Maybe that is messing up the way the backpack detects when to regen.  Not sure why O would cause it to activate/deactivate though, unless it is some kind of obscure Adventure Backpacks feature.

**Comment by richardhendricks** [comment] 2019-02-04 07:49
Just had another thought - what if the problem isn't AB giving regen, but some other mod causing player damage?  Blood magic or something else that causes a hurt-self action?

**Comment by Lithorn** [comment] 2019-02-04 09:34
O only activates, wont deactivate. I do have 1 tinker canister and have tried with it on/off, no difference.

**Comment by Ugachaga** [comment] 2019-02-04 09:56
By default Tinkers Construct "Armor GUI" keybind is O. Try to change it.

**Comment by draknyte1** [comment] 2019-02-04 12:01
Commenting just to loop myself into this discussion; because I’m curious which dev done did fucked up. 🤨

**Comment by Lithorn** [comment] 2019-02-04 17:13
2.0.6.7DEV seems to have corrected the issue? Its no longer giving me regen when pressing O. Changing Tcon key didn't affect it me thinks. Gona relaunch client and test again.

**Comment by Lithorn** [comment] 2019-02-04 18:06
Unable to get it going again in 2.0.6.7Dev. Seems to have fixed itself? Nothing really changed in the control area.. As stated above, only lowered ram use..

**Comment by Lithorn** [comment] 2019-02-10 05:43
I have more data. It is related to Travlers gear. It was set to O as well. So I changed it to N6 and low and behold, pressing that gave me regen.

**Comment by Ugachaga** [comment] 2019-02-12 14:09
I still cannot reproduce it locally with Travellers Gear, Adventure Backpack and Tinkers Cobstruct (with or w/o health canisters). Obviously some other mod(s)/states are involved.

Try to empty all the equipment slots showing on TG screen (canisters, baubles, armor... all of them), transfer everything from the player's inventory to some chest, restart the world and open TG inventory.

**Comment by Dream-Master** [comment] 2019-02-12 14:26
@Lithorn waiting on your update here to see if we can close it.

**Comment by Lithorn** [comment] 2019-02-12 18:56
It seems to happen on and off. I canno't narrow it down either. I recently changed the key for the TG and when I began using it I started getting the regen buff. Now it dosen't seem to do it.

**Closed** 2019-08-30 19:54 UTC
Labels: can't reproduce, help wanted, question
