### ISSUE TITLE
Ticking block entity crash

### ISSUE THREAD

**Issue by liquorice-wb** [GTNewHorizons/NewHorizons#2477] opened 2018-01-21 03:31 UTC
Latest version (2.0.2.7)
Hard crash caused by BoP wild carrots (possibly could be repeated by other BoP crops but the carrots are the only crash I've come across yet). 
I only just updated to 2.7 today and haven't had this particular crash before in older versions.
Temp fix: config > forge.cfg > change removeErroringEntities and removeErroringTileEntities to true

Crash report:
```
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 3
	at lokko12.berriespp.crops.BoP.WildCarrotsCrop.attributes(WildCarrotsCrop.java:38)
	at ic2.core.crop.TileEntityCrop.calculateRatioFor(TileEntityCrop.java:415)
	at ic2.core.crop.TileEntityCrop.attemptCrossing(TileEntityCrop.java:311)
	at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:174)
	at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lokko12.berriespp.crops.BoP.WildCarrotsCrop.attributes(WildCarrotsCrop.java:38)
	at ic2.core.crop.TileEntityCrop.calculateRatioFor(TileEntityCrop.java:415)
	at ic2.core.crop.TileEntityCrop.attemptCrossing(TileEntityCrop.java:311)
	at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:174)
	at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
	Name: TECrop // ic2.core.crop.TileEntityCrop
	Block type: ID #215 (blockCrop // ic2.core.crop.BlockCrop)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-49,63,-375), Chunk: (at 15,3,9 in -4,-24; contains blocks -64,0,-384 to -49,255,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #215 (blockCrop // ic2.core.crop.BlockCrop)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
description: Ticking block entityjava.lang.ArrayIndexOutOfBoundsException: 3at lokko12.berriespp.crops.BoP.WildCarrotsCrop.attributes(WildCarrotsCrop.java:38)at ic2.core.crop.TileEntityCrop.calculateRatioFor(TileEntityCrop.java:415)at ic2.core.crop.TileEntityCrop.attemptCrossing(TileEntityCrop.java:311)at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:174)at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122)at net.minecraft.world.World.func_72939_s(World.java:1939)at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- Head --Stacktrace:at lokko12.berriespp.crops.BoP.WildCarrotsCrop.attributes(WildCarrotsCrop.java:38)at ic2.core.crop.TileEntityCrop.calculateRatioFor(TileEntityCrop.java:415)at ic2.core.crop.TileEntityCrop.attemptCrossing(TileEntityCrop.java:311)at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:174)at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122)at net.minecraft.world.World.func_72939_s(World.java:1939)-- Block entity being ticked --Details:Name: TECrop // ic2.core.crop.TileEntityCropBlock type: ID #215 (blockCrop // ic2.core.crop.BlockCrop)Block data value: 0 / 0x0 / 0b0000Block location: World: (-49,63,-375), Chunk: (at 15,3,9 in -4,-24; contains blocks -64,0,-384 to -49,255,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)Actual block type: ID #215 (blockCrop // ic2.core.crop.BlockCrop)Actual block data value: 0 / 0x0 / 0b0000Stacktrace:at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
```

**Comment by mitchej123** [comment] 2018-01-21 03:54
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/2458 I believe

**Comment by Dream-Master** [comment] 2018-01-21 08:33
and it is fixed allready in dev

**Comment by bartimaeusnek** [comment] 2018-01-22 14:48
its already fixed:
please update your berries++ to this version:
https://github.com/bartimaeusnek/berries-plus-plus/releases/tag/1.1.1d

**Closed** 2018-03-10 10:00 UTC
Labels: FixedInDev, duplicate
