### ISSUE TITLE
Radon Decay quest impossible.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3616] opened 2018-09-13 04:51 UTC
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Get radium 226 dust into my inventory for quest retrieval task.

Quest to go "Alright you can stop bothering with this low tier quest and continue the game."
#
#### What happend instead? (Attach screenshots if needed)
The radium decays instantly upon picking up, making it impossible or unnecessarily difficult to complete the quest.
#
#### What do you suggest instead/what changes do you propose?
The radium 226 dust to decay slower like it's suppose to, or the quest to not require holding the dust.

**Comment by Dream-Master** [comment] 2018-09-13 06:30
duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/3582

**Comment by Teirdalin** [comment] 2018-09-13 08:45
So judging from that post ages ago- does this only effect certain people or is this a problem everyone has?

**Comment by Dream-Master** [comment] 2018-09-13 08:56
It effects server player so far i know. In single player all fine.

**Closed** 2019-08-30 18:13 UTC
Labels: duplicate
