### ISSUE TITLE
Crash when clicking on T1 Heavy Duty Plates in the questbook

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5691] opened 2020-03-04 22:57 UTC
#### Which modpack version are you using?
2.0.8.5dev
#
#### What did you try to do, and what did you expect to happen?
Click on T1 Heavy Duty Plates in the questbook, see recipe.
Quest is the one on the space race tab.
#
#### What happened instead? (Attach screenshots if needed)
Click on T1 Heavy Plates in the questbook, crash
[crash-2020-03-04_17.37.35-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4289979/crash-2020-03-04_17.37.35-client.txt)
#
#### What do you suggest instead/what changes do you propose?

Fix it.

**Comment by mitchej123** [comment] 2020-03-04 23:00
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/5559

**Closed by mitchej123** 2020-03-04 23:00 UTC
