### ISSUE TITLE
Galacticcraft wire can charge over capacity in some machine

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#1276] opened 2017-04-04 15:01 UTC
While use GC wire to charge industrial apiary i found it can charge over capacity and same problem in AE Charger
![2017-04-04_22 53 39](https://cloud.githubusercontent.com/assets/25171639/24663479/9aa713f0-198a-11e7-9de0-3097d5f5e9be.png)

![2017-04-04](https://cloud.githubusercontent.com/assets/25171639/24663493/a4bc7ce0-198a-11e7-83b6-6240273ebb43.png)

**Comment by FallDark** [comment] 2017-04-04 15:07
![2017-04-04](https://cloud.githubusercontent.com/assets/25171639/24663740/5ab53d20-198b-11e7-9c01-63986d4bcd72.png)
![2017-04-04_22 54 25](https://cloud.githubusercontent.com/assets/25171639/24663772/724939b4-198b-11e7-92b9-1f3b9c8c348e.png)

**Comment by Dream-Master** [comment] 2017-04-04 15:12
Ok will do the cable more expensive

**Comment by Bryfer** [comment] 2017-04-04 15:21
isnt the cabled needed when making GC machinery?

**Comment by Dream-Master** [comment] 2017-04-04 15:32
not sure but some recipes use it. What you think when i add Meteoric Iron and/ir Titanium or Tungesten Seel to it ? Or make it in a IV Machine ? @FallDark  @Bryfer

**Comment by Bryfer** [comment] 2017-04-04 15:49
Changing the recipe will not fix the problem, however I can recommend you to take a look in the power-GC3.conf of Galacticraft, and see over these settings
# Configuration file

compatibility {
    D:"BuildCraft Conversion Ratio"=16.0
    B:"Disable INPUT of BuildCraft energy"=false
    B:"Disable INPUT of IC2 energy"=false
    B:"Disable INPUT of Mekanism energy"=false
    B:"Disable INPUT of RF energy"=false
    B:"Disable OUTPUT of BuildCraft energy"=false
    B:"Disable OUTPUT of IC2 energy"=false
    B:"Disable OUTPUT of Mekanism energy"=false
    B:"Disable OUTPUT of RF energy"=false
    B:"Disable old Buildcraft API (MJ) interfacing completely?"=false
    D:"IndustrialCraft Conversion Ratio"=6.557376861572266
    I:"Loss factor when converting energy as a percentage (100 = no loss, 90 = 10% loss ...)"=100
    D:"Mekanism Conversion Ratio"=0.6557376980781555
    D:"RF Conversion Ratio"=1.600000023841858
}


display {
    B:"If BuildCraft is loaded, show Galacticraft machines energy as MJ instead of gJ?"=false
    B:"If IndustrialCraft2 is loaded, show Galacticraft machines energy as EU instead of gJ?"=true
    B:"If Mekanism is loaded, show Galacticraft machines energy as Joules (J) instead of gJ?"=false
    B:"Show Galacticraft machines energy in RF instead of gJ?"=false
}

**Comment by Dream-Master** [comment] 2017-04-04 15:58
@Bryfer What you suggest to change?

**Comment by Bryfer** [comment] 2017-04-04 16:18
Changing Disable OUTPUT to true should disable gc from converting power to other mods.
since Disable INPUT is still set to false, gc should still be able to recive power from gt as intended.


Im off to work now, Ill test these changes once I get home unless someone else has already checked it

**Comment by Bryfer** [comment] 2017-04-05 12:19
Changing the four output values to true disables GC from feeding power into other mods. Still able to power GC machines.
![image](https://cloud.githubusercontent.com/assets/22825059/24704851/a477e9f2-1a09-11e7-9a04-5de6e582eda9.png)
![image](https://cloud.githubusercontent.com/assets/22825059/24704859/b23a2e1a-1a09-11e7-8737-c29d170c81e6.png)
![image](https://cloud.githubusercontent.com/assets/22825059/24704865/b887e730-1a09-11e7-808b-4479ba51a57f.png)

However while testing I also noticed that the main issue here isnt with the GC cables. the same overcharge can be achived with GT cables aswell when sending large amounts of voltages into an machine. This picture below send 1tick of LuV (32768eu) voltage into both the (GenDustry)Industrial Apiary and (AE2)Charger. However it does not charge it again unless the energy levels to below the "max" level.
![image](https://cloud.githubusercontent.com/assets/22825059/24705031/57f7eb44-1a0a-11e7-91b5-fd0986cd7382.png)


Conclusion; My fix disabled GC from powering other mods, Forcing players to use the Correct GT cables instead, However it does not solve this issue.

**Comment by Methes** [comment] 2017-04-05 16:23
Does it cause any error code wise or is just esthetic problem?
If there's no problem in overcharging those RF machines I don't see it as an issue.

**Comment by Dream-Master** [comment] 2017-04-05 16:45
If you can use this cable on gt  machines it is a issue.

**Comment by Methes** [comment] 2017-04-06 04:45
I was just refering to this which, while being an error, should not be an issue:

> Conclusion; My fix disabled GC from powering other mods, Forcing players to use the Correct GT cables instead, However it does not solve this issue.
The machines should explode when they are given too high voltage, but since they can not explode they accept the power correctly instead causing this issue.

Btw. I thought GC cables can't power GT machines and this was only about GC cables powering RF machines. Am I wrong?

**Comment by Bryfer** [comment] 2017-04-06 13:20
> If you can use this cable on gt machines it is a issue.

From my testing after config changes I've found that GalacticCraft Core Aluminum Wire ..
can no longer be used to power IC2, GT, AE2, EnderIO or Gendustry

can be used to power GC machines(intended) and Forestry machines (not intended, and cant be fixed with config)

**Comment by Dream-Master** [comment] 2017-04-06 13:39
@Bryfer can you post the lastes cfg file her so i can change it?

**Comment by Bryfer** [comment] 2017-04-06 14:02
# Configuration file

compatibility {
    D:"BuildCraft Conversion Ratio"=16.0
    B:"Disable INPUT of BuildCraft energy"=false
    B:"Disable INPUT of IC2 energy"=false
    B:"Disable INPUT of Mekanism energy"=false
    B:"Disable INPUT of RF energy"=false
    B:"Disable OUTPUT of BuildCraft energy"=true
    B:"Disable OUTPUT of IC2 energy"=true
    B:"Disable OUTPUT of Mekanism energy"=true
    B:"Disable OUTPUT of RF energy"=true
    B:"Disable old Buildcraft API (MJ) interfacing completely?"=false
    D:"IndustrialCraft Conversion Ratio"=6.557376861572266
    I:"Loss factor when converting energy as a percentage (100 = no loss, 90 = 10% loss ...)"=100
    D:"Mekanism Conversion Ratio"=0.6557376980781555
    D:"RF Conversion Ratio"=1.600000023841858
}


display {
    B:"If BuildCraft is loaded, show Galacticraft machines energy as MJ instead of gJ?"=false
    B:"If IndustrialCraft2 is loaded, show Galacticraft machines energy as EU instead of gJ?"=true
    B:"If Mekanism is loaded, show Galacticraft machines energy as Joules (J) instead of gJ?"=false
    B:"Show Galacticraft machines energy in RF instead of gJ?"=false
}

**Closed** 2017-04-17 09:53 UTC
Labels: FixedInDev
