### ISSUE TITLE
Stone Duplicates With Fortune / Auto-Smelt

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3499] opened 2018-08-24 06:02 UTC
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
*Mined stone with my pickaxe with fortune and auto-smelt.
*Get a single block of stone back.
#
#### What happend instead? (Attach screenshots if needed)
Gotten a few stones instead.
#
#### What do you suggest instead/what changes do you propose?
Change number of stone from breaking it.

This is a fairly minor issue really considering how easy it is to get stone for anyone at that point.

**Comment by draknyte1** [comment] 2018-08-24 06:05
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/3497... not a bug, but a config issue.

**Closed** 2018-08-24 06:27 UTC
Labels: FixedInDev

**Comment by Teirdalin** [comment] 2018-08-24 06:28
Sorry, thought it didn't post earlier. lol

**Comment by Dream-Master** [comment] 2018-08-24 06:28
np
