### ISSUE TITLE
Questing Issue (Tier 3, Molten Polyethylene)

### ISSUE THREAD

**Issue by Disssy** [GTNewHorizons/NewHorizons#1919] opened 2017-09-05 01:22 UTC
#### Which modpack version are you using?
1.5.1.0
#### If in multiplayer; On which server does this happen? 
N/A
#### What did you try to do, and what did you expect to happen?
I was trying to progress in the questbook
#### What happened instead? (Attach screenshots if needed)
In the quest titled "Molten Polyethylene" in Tier 3, the second requirement to complete the quest is a (to my knowledge) unobtainable Universal Fluid Cell
#### What do you suggest instead/what changes do you propose?
Change it to something you can actually get legitimately :P

**Comment by Bryfer** [comment] 2017-09-05 02:40
Similar to #1891

**Comment by Dream-Master** [comment] 2017-09-05 18:44
@Disssy @Bryfer in which canister/can/cell you can fill molten plastic(polyethylen)?

**Comment by SirAzazel** [comment] 2017-09-06 09:03
@Dream-Master, @Bryfer already commented this as duplicate of #1891

**Comment by Dream-Master** [comment] 2017-09-06 09:55
But how you can obtain this cells?

**Comment by Bryfer** [comment] 2017-09-06 11:07
@Dream-Master Really? 
As far as I know there is still a limit for how many types of cells there can be in the game.
I assume this is one of those liquids that was chosed not to be included. I dont know if there is a fix. but if you actually check #1891 
you can find comments like 

> Actually, found it works with Universal Fluid Cells and not the regular Empty Cells like I had

> No way to make Cells contain any other fluids? Universal Fluid Cells really are bad. They don't work well (if at all iirc) when automating GT machines, they are finicky, and their recipes don't even show up in NEI. Thus few people would know how to even complete the mentioned quest..

> Most likely the same issue as with glue some time ago the fluid id missmatches in the recipe and registry

I also remember that we had issues with Universal cells earlier in quests and that is why I made this #1089 back in febuary.

also there is no need to have two very similar issues up, so as SirAzazel and I already wrote. This is a dupe of #1891, and therefore it should already be closed? so we can keep the discussions about this issue in one place.

**Comment by Dream-Master** [comment] 2017-09-06 11:47
@technus we need molten fluids in gt cells in code.

**Comment by Dream-Master** [comment] 2017-09-06 19:42
it is possible to grab universal cells and fill them in tanks to get this cells

![image](https://user-images.githubusercontent.com/2970688/30131207-38802540-934c-11e7-9dd7-d5131003c8cb.png)
![image](https://user-images.githubusercontent.com/2970688/30131210-3d1a15a2-934c-11e7-980d-9172bd445ba7.png)

**Comment by Dream-Master** [comment] 2017-09-06 19:42
You can use this to flish the Quest

**Comment by SirAzazel** [comment] 2017-09-07 07:49
maybe its better to change quest to use some other container instead rather than 'invent a bicycle' by making people use tanks?

**Comment by Dream-Master** [comment] 2017-09-07 08:15
Make a suggestion how i could change the Quest? How i can detect this fluid because fluid task are not working very nice.

**Comment by Dream-Master** [comment] 2017-09-28 10:40
I remove the fluid so far i rember. Need to test it again.

**Closed** 2017-12-14 11:44 UTC
Labels: duplicate, FixedInDev
