### ISSUE TITLE
ZPM+ lootbag need items

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4288] opened 2019-03-19 17:01 UTC
#### Which modpack version are you using?
2.0.5.1-2.0.7.x
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
i open ZPM-UV lootbag
#
#### What happend instead? (Attach screenshots if needed)
i got a diamond.
#
#### What do you suggest instead/what changes do you propose?
ZPM+ loot bag should have a good reward like UV circuit or UHV superconductor ....etc we should open a discussion and make it balance.

**Comment by Namikon** [comment] 2019-03-20 06:14
Duplicate of #4268

**Comment by Dream-Master** [comment] 2019-03-20 07:14
not a real duplicate. zpm and uv bags need items

**Comment by Namikon** [comment] 2019-03-20 07:56
But it's the same topic; That LootBags are merged with Trash and appear to be unfair. That affects every Lootbag tier; Except Legendary

**Comment by BlackFlameTNT** [comment] 2019-03-20 08:20
Zpm+ loot bag give only 1 diamond there is nothing else

**Comment by Dream-Master** [comment] 2019-03-20 08:30
no zpm lootbags are add to quests but have no items or only the diamond

**Comment by BlackFlameTNT** [comment] 2019-03-20 08:39
Fusion quest line give you zpm+ lootbag and the only item they give is a single diamond even if it is fortunate III.

**Comment by Namikon** [comment] 2019-03-20 08:46
Ok, seems I have to rename the Diamond to "The Dev forgot to add Items to me"

**Closed** 2019-08-30 20:16 UTC
Labels: RFC (request for comment), suggestion
