### ISSUE TITLE
Tool Forge quests [1.4.1.1]

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1384] opened 2017-05-04 01:06 UTC
quest: Cutting a Tree log by log is so Old School

I have crafted steel LumberAxe and the quest did not register this as a completed task. So basically it cannot be completed. I assume that Hammer and Excavator quests will have the same problem.

Suggestion: let it accept any LumberAxe made from any material, because it at this point you have EBF and you can use much better materials than steel (like Cobalt).

**Comment by bigbass1997** [comment] 2017-05-04 01:20
This issue is a duplicate of #1366 

In the future please use Github's search features to look for similar issues to the one you want to post, before posting. But thank you anyways for bringing this to our attention.

**Closed by bigbass1997** 2017-05-04 01:20 UTC
Labels: duplicate
