### ISSUE TITLE
GT>RF conversion catches fire

### ISSUE THREAD

**Issue by TechnicianLP** [GTNewHorizons/NewHorizons#1904] opened 2017-08-30 19:05 UTC
V: 1.5.1.0
Private Server with friends

- We noticed that when we connect wires to a forestry-farm-gearbox it would convert the gregtech power we have to RF
- but then the 4x Tin Cables we used caught fire
- we were thinking it might have been a stray packet due to use having a 9Slot-Battery buffer with 8 batteries in the basement, but after dedicating a 1 slot battery buffer to the farm and connecting it up with 4x Tin Cables again, they still caught fire a short while after 
- we tried using 1x Copper Wires which also catched fire
- does not make sense at all due to the buffer only being able to output 1 ampere (and it isnt caused by voltage either - lv battery buffer)
We have a temporary workaround with a hobbyists steam engine though.

**Comment by Radst0ne** [comment] 2017-08-30 20:06
I noticed that too that cables can burn sometimes (but rarely) even if they a big enough, I think it has something todo with chunk boarders and loading/unloading chunks maybe even lag
Not sure though.

**Comment by Drobac** [comment] 2017-08-30 20:17
Its a problem with chunk borders, its an isaue of one chunk running faster then the other due to distance from player. You can fix it by either chunkloading both chunks or using transformers/machine hulls on both sides of the chunk border

**Comment by TechnicianLP** [comment] 2017-08-30 20:49
Define "running faster" please - afaik all loaded chunks run with the same speed/tps regardless of player-vicinity

**Comment by SirAzazel** [comment] 2017-08-31 09:14
you see not only world has TPS, Different chunks have different update times, thus pretty much different TPS

**Comment by Methes** [comment] 2017-08-31 10:23
I believe this setup is only on official servers due to specific plugins, isn't it? This shouldn't be an issue for private server then (unless it uses the same plugins).

**Comment by TechnicianLP** [comment] 2017-08-31 10:23
If that were how Minecraft worked TickThreading wouldn't be neccessary .... (which would be awesome performancewise)
Minecraft only uses a single Thread for its core functionality - this thread ticks all worlds and tileentites/entites within them in sequence (after which it processes packets and does some other stuff ...) key point is: all tileentites in each world get updated in the order they were loaded in (which is not neccessarily grouped to chunks if for example a tileentity gets added (to the end of the list)) - this is where the problem comes in: if one runthrough of ticking everything takes longer than 50ms the tps will go down - not just for one chunk - for every world, chunk, packethandler and whatever else gets updated by the main gameloop

**Comment by SirAzazel** [comment] 2017-08-31 11:38
You remember great mod named Opis that been showing loaded chunks and chunk timings (and separate (tile)entities too)? i didnt say its same as TPS, rather than its time it takes for chunk to realise it shouldve ticked, somewhat 'ping' that is based on how much lag tileents create

**Comment by TechnicianLP** [comment] 2017-08-31 11:47
i get your point that different tileentites (or groups of them added together by mods) take different amounts of time to update - nevertheless can no tileentity go ahead of any other one

**Comment by Drobac** [comment] 2017-09-01 15:19
Check with @Namikon, but Cauldron which is in our server pack work a bit different from what i know. Chunk further from the player have slower updates and it causes the wire burnout

**Comment by Technus** [comment] 2017-09-01 15:32
the issue is indeed by tick rate differencies, newest builds of GT should have that issue fixed

**Comment by Technus** [comment] 2017-09-01 15:32
but i am still waiting for the builds to get on the servers so i ca check if my "fix" works

**Comment by Dream-Master** [comment] 2017-09-04 18:21
So what we can do here ?

**Comment by bigbass1997** [comment] 2017-09-11 04:47
Seems to be a lot of speculation here about what exactly causes this strange behavior. What Drobac mentioned is correct. Cauldron adds a special option that reduces the tickrate of TileEntities in chunks that are not force loaded and do not contain a player in them. Meaning that if I build a coke oven in one chunk, and a second in an adjacent chunk, then stand in the first chunk, the coke oven I am standing with will actually tick faster than the one in the adjacent chunk.

Same goes for GT Cables, Machines, etc. What happens then is that while power is flowing through a cable line which crosses into another chunk, one chunk's cables may be ticking faster than those in the next chunk, causing the appearance of over-amperage along the line, which can cause cables to burn, even with a single Amp initially.

Now the official servers have this feature enabled because it does in fact increase TPS performance and TPS stability. Other servers that run Cauldron (aka run bukkit in some form with the modpack) might have this feature enabled as well. Thus, this tickrate causing cables to burn issue does not happen in single player either.

As Tec mentioned, he attempted to implement a "fix" of sorts that may prevent cables from over-amperage due to the varying tickrates, however it just needs to be tested. But in response to the original post, IF your problem is indeed this tickrate varying issue, then it might be resolved with the 2.0 update, or by disabling the feature in one of the bukkit config files. As Drobac also pointed out, a workaround for this is either force chunkload the chunks, or setup a step-up then step-down transformer set on each side of the chunk border, or use two battery buffers. If none of this works, then please let us know, otherwise I think this issue can be closed.

**Comment by SirAzazel** [comment] 2017-09-11 10:19
Tec's Fix seemd to not work on delta as mentioned by @bartimaeusnek in #chat_zeta

**Comment by Dream-Master** [comment] 2017-09-11 16:40
@Technus

**Comment by Dream-Master** [comment] 2017-09-28 10:44
@TechnicianLP is this fixed ?

**Closed** 2017-10-08 11:13 UTC
Labels: FixedInDev
