### ISSUE TITLE
Magnetite to Iron recipe is wrong

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1955] opened 2017-09-12 23:32 UTC
#### If in multiplayer; On which server does this happen? 
Epsilon

Recipes say that Impure pile of magnetite or usual Magnetite dust will give me 1 iron ingot but in fact they give 6 nuggets.

**Comment by Bryfer** [comment] 2017-09-12 23:49
similar to #1948

**Comment by Dream-Master** [comment] 2017-09-13 08:10
This I a change. Ebf and bbf give full ingot

**Comment by SirAzazel** [comment] 2017-09-13 08:22
Im very sorry for all adequate people that hate (like i do) when people respond to duplicate issues, but **DREAM WHY THE FCK YOU CANT SEE THAT ITS DUPLICATE OF #1948 AND JUST CLOSE IT INSTEAD OF COMMENTING ON IT AND ADDING STUPID LABELS**

**Comment by Dream-Master** [comment] 2017-09-13 08:25
Languge

**Comment by SirAzazel** [comment] 2017-09-13 08:35
oh, im sorry, but its not swear here, its one of those moments where swear words become required part of sentence. Github allows profanity, and this is public place, thus you cannot force me to use or not use profanity where i feel like its required.

**Closed** 2017-09-13 09:17 UTC
Labels: Not a Bug
