### ISSUE TITLE
Cable system calculates incorrect Amperage

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2094] opened 2017-10-16 06:49 UTC
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
![image](https://user-images.githubusercontent.com/4941736/31598550-f23e0442-b256-11e7-8580-f1e847034c87.png)
On the screenshot you can see 4a battery buffer. 4x Copper Cable and 2 Energy Hatch.
According to all wikis everything was done correct.
4a battery buffer should output MAX 4a.
1 Energy Hatch according to ingame description should accept MAX 2a. So 2 energy hatches MAX 4a.
And there is no cable crossing chunk border.

But that cable that you see missing has burnt 3(!!!) times.
Because of such situation yesterday I had the whole base explode.

**Comment by Dream-Master** [comment] 2017-10-16 07:19
@Technus any idea here?

**Comment by Technus** [comment] 2017-10-16 08:03
Might be resolved with the prev. Wire fix

**Comment by Dream-Master** [comment] 2017-10-16 08:05
Will do an update later.

**Comment by nikitinalexx** [comment] 2017-11-03 21:51
Got this problem reproduced in Single Player.
4 Advanced Steam Turbine.
4 Battery Buffer.
2 Energy Hatch.
4A cable.

Got explosion of this EBF right in front of me when i came close to it to input some dust.
Here is a screenshot of my setup before explosion.
![image](https://user-images.githubusercontent.com/4941736/32397298-df181278-c0f1-11e7-9ff6-4d16bb888475.png)
Here are chunk borders. I am looking at the NORTH (if this matters).
![image](https://user-images.githubusercontent.com/4941736/32397315-f335e8c0-c0f1-11e7-9641-bb3395ece3f8.png)

**Comment by richardhendricks** [comment] 2017-11-04 03:54
Kebal,
I tried in a creative world to get an explosion to happen but was unable to cause an explosion.  I flew away 1000 blocks and back.  I also moved the world spawn 1000 blocks away in case the chunks were staying loaded the whole time. After that I flew away and came back several times without issue.

[gregtech-5.09.32.09.zip](https://github.com/GTNewHorizons/NewHorizons/files/1442908/gregtech-5.09.32.09.zip)

  Here is a test build of gregtech with some debug messages added around wire overvoltage and machine explosions.  Try running it with your save and report back what you see in gregtech.log

Now, this is a slightly newer version than what is available in 2.0.1.3, but I don't think any of the recent changes did anything with the wires.  It does include modified oregen, but shouldn't cause issues related to this.

The debug messages are always on, you don't need to change anything in the gregtech.cfg file. They are:

                    aBaseMetaTileEntity.setToFire();
					GT_Log.out.println(
						"Cable set on fire due to overheating!"
						);


                        if (GregTech_API.mRFExplosions && ((IEnergyReceiver) tTileEntity).getMaxEnergyStored(tDirection) < rfOut * 600) {
                            if (rfOut > 32 * GregTech_API.mEUtoRF / 100) {
								this.doExplosion(rfOut);
								GT_Log.out.println(
									"Explosion caused by rf processing?"
								);
                            }
                        }

        World tWorld = getBaseMetaTileEntity().getWorld();
        tWorld.setBlock(tX, tY, tZ, Blocks.air);
        if (GregTech_API.sMachineExplosions)
            tWorld.createExplosion(null, tX + 0.5, tY + 0.5, tZ + 0.5, tStrength, true);
		GT_Log.out.println( "Boom today!");


My build crossing chunk boundaries

![2017-11-03_20 06 49](https://user-images.githubusercontent.com/1214811/32401999-23ebecde-c0e9-11e7-8c19-f57c16647d41.png)

**Comment by Dream-Master** [comment] 2017-12-01 11:06
If still exist we can reopen it.

**Closed by Dream-Master** 2017-12-01 11:06 UTC
Labels: question
