### ISSUE TITLE
[Galacticraft] Landing in asteroid belt spawns at the wrong coordinates

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2194] opened 2017-11-14 12:16 UTC
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Travel to Asteroids.
#
#### What happend instead? (Attach screenshots if needed)
![aster](https://user-images.githubusercontent.com/23512002/32779346-70cddb08-c94e-11e7-9991-911225924efe.png)
Look at the coordinates in the top-right corner
#
#### What do you suggest instead/what changes do you propose?
There is a related issue at GC github but it is closed. I suggest providing them with GCAsteroidData.dat and reopening the issue. https://github.com/micdoodle8/Galacticraft/issues/2271

**Comment by Methes** [comment] 2017-11-14 13:01
Happend to me on Delta too.
This is especially problem when travelling back to Overworld, as you land far beyond the border, not only overloading the server with chunkgeneration (and disconnecting everyone), but also losing your rocket due to instant teleport back to the border while the rocket remains beyond.

**Comment by repo-alt** [comment] 2017-11-14 13:58
Well, on Epsilon you don't get teleported to the border, but can't fly back anyway, because the rocket does not recognize fuel loader at these coordinates.

**Comment by Dream-Master** [comment] 2017-11-18 15:25
Not sure if i can do here anything. Is this reported to original GC repo?
@repo-alt 
@Methes

**Comment by repo-alt** [comment] 2017-11-18 15:41
I'll just quote the report: There is a related issue at GC github but it is closed. I suggest providing them with GCAsteroidData.dat and reopening the issue. micdoodle8/Galacticraft#2271

**Comment by Dream-Master** [comment] 2017-11-18 15:58
GCAsteroidData.dat ? Where I can found it? @repo-alt

**Comment by repo-alt** [comment] 2017-11-18 20:18
"GCAsteroidData.dat - it's in the data folder in your world save folder"

**Comment by Dream-Master** [comment] 2017-11-19 00:37
Ok will do

**Comment by repo-alt** [comment] 2017-11-19 12:52
Thanks Martin, for bothering with that even on vacation :)

**Comment by Dream-Master** [comment] 2017-11-30 11:42
[GCAsteroidData.zip](https://github.com/GTNewHorizons/NewHorizons/files/1517589/GCAsteroidData.zip)

**Comment by Dream-Master** [comment] 2017-11-30 11:42
from Delta @repo-alt

**Comment by MJRLegends** [comment] 2017-12-01 19:41
Is anyone able reproduce this will just normal forge and not thermos?

**Comment by spylor** [comment] 2017-12-11 17:46
I'm not sure if this is the same issue. But If is launch from the same pad on overworld my capsule on the asteroids would land on another asteroid each time. The closest ones, but at least 3 different once and never the platform I had build. Using a launch controller after this solved this problem ofc. I'm using 119 of galaxycraft on forge 1.11.2 the newest version.

**Comment by Dream-Master** [comment] 2018-08-11 16:43
gc development stopped. Ok we fork the repo but no one takes care of it. I close this now

**Closed by Dream-Master** 2018-08-11 16:43 UTC
Labels: help wanted
