### ISSUE TITLE
Crash (Multiplayer, 1.5.0.4)

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1651] opened 2017-07-11 21:32 UTC
Crashreport:
https://pastebin.com/nasjyKY9

Happens when other Player (local MP) tries to look up a recipe (host not affected) (doesnt matter which recipe)
Did not happen in 1.5.0.2
1.5.0.3 not tested atm

**Comment by WarlordWossman** [comment] 2017-07-12 00:13
I just crashed on a server in 1.5.0.4 when I tried to check a recipe. Nobody else on the server. 
Already sent the crashreport to Dream.

**Comment by Dream-Master** [comment] 2017-07-12 07:36
Yes since  1.5.0.3 we have this mysterious crashes.

**Comment by Ugachaga** [comment] 2017-07-12 08:28
Can you confirm or deny if crash related with Adventure Backpack and happens only if recipe view called from backpack GUI?

**Comment by Radst0ne** [comment] 2017-07-12 09:41
Cant confirm that, happens everywhere

**Comment by Dream-Master** [comment] 2017-07-12 10:00
@Ugachaga i update to version 15 before we stay at 12

**Comment by Dream-Master** [comment] 2017-07-12 10:01
@Ugachaga the crash not give much infos about stactrace

**Comment by Ugachaga** [comment] 2017-07-12 13:09
@Dream-Master  
`func_99999_d() = run()` and `func_71411_J = runGameLoop()`, something derping rly hard.

**Comment by Dream-Master** [comment] 2017-07-12 16:39
What this function describes?

**Comment by Raccoon2709** [comment] 2017-07-12 16:45
the functions from invetory tweaks

**Comment by Namikon** [comment] 2017-07-12 18:02
Still not sure which mod exactly is causing it, but at least I got a more detailed Stacktrace:
https://pastebin.com/SL1sC1ak

**Comment by Lainiel** [comment] 2017-07-12 21:51
My game crashed 4 times when I updated to 1.5.0.3 and tried to open recipe in NEI after joining my server. Then I tried starting the game and creating a new world in singleplayer to see if the game crashes too. When I opened NEI recipe in singleplayer my game didn't crash. After that I joined my server again and everything worked. I have been playing 1.5.0.3 for more than a day and haven't had any issues yet. I told my friend to do the same thing (create a singleplayer world open up a recipe in NEI and then join the server) and his game stopped crashing too.

**Comment by Dream-Master** [comment] 2017-07-17 08:09
I will release 1.5.0.5 soon with a never gt++ version. Lets see if this fix this issue.

**Comment by Namikon** [comment] 2017-07-17 12:21
Then close it when the issue is solved

**Comment by Dream-Master** [comment] 2017-07-17 14:54
Not sure why it was closed maybe auto closed.

**Comment by Dream-Master** [comment] 2017-07-19 17:47
seems to be fixed.

**Closed** 2017-07-22 22:30 UTC
Labels: FixedInDev
