### ISSUE TITLE
Obsidian Duplication Glitch

### ISSUE THREAD

**Issue by CloudStyles** [GTNewHorizons/NewHorizons#785] opened 2016-11-15 19:17 UTC
Long Story short,
AutoSmelt Pickaxe, mine an obsidian block, recieve 9 ingots for it, place in tinkers construct smeltery, use 2 ingots for another block of obsidian, place and mine for another 9. Infinite obsidian.
Bug. Not sure if game breaking, but being able to do this before lv machines is a little op.

**Comment by Technus** [comment] 2016-11-15 19:23
@Dream-Master Check if u can correct with scripts.

**Comment by Dream-Master** [comment] 2016-11-16 15:41
I can't reproduce it. Make me a pick with a lava crystal to get auto smelt. Mining Vanilla Obsidian Block get an Obsidian Block back.
@CloudStyles Can you send me some pics please

**Comment by Dream-Master** [comment] 2016-11-16 15:42
![image](https://cloud.githubusercontent.com/assets/2970688/20353557/91cdeca4-ac1b-11e6-95a2-df29eeaea487.png)
![image](https://cloud.githubusercontent.com/assets/2970688/20353561/97c7f118-ac1b-11e6-9e00-e9c354f535ab.png)

**Comment by Technus** [comment] 2016-11-18 23:10
Related to fortune+autosmelt issues i guess

**Comment by Dream-Master** [comment] 2016-11-18 23:17
No. Not works with Autosmelt and Luck too.

![image](https://cloud.githubusercontent.com/assets/2970688/20450038/8e668570-aded-11e6-94a3-beb24aede07e.png)

**Comment by Dream-Master** [comment] 2016-11-18 23:21
@CloudStyles 
I need more infos here and a pic from your pick.

**Comment by CloudStyles** [comment] 2016-11-18 23:23
I fear it mayhave happened due to a server file glitch, will update tomorrow when I can review and repeat the process and will debunk if server messup caused this

**Comment by Dream-Master** [comment] 2016-11-18 23:25
ok.

**Comment by Dream-Master** [comment] 2016-11-20 11:59
@CloudStyles So can i close this ?

**Closed** 2016-11-27 14:08 UTC
Labels: can't reproduce
